### ISSUE TITLE
Can't import some CSV files in latest version of Rill Developer

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1002]
**Describe the bug**
We want to maintain parity with older versions of Rill Developer.  Rill 0.9.0 can import these files, but Rill 0.11.0 sometimes imports 0 rows.

**To Reproduce**
1. create the following 4 csv files:

*in.csv*
"country_code"
"IN"
"IN"

*us.csv*
"country_code"
"US"
"US"

*empty-string.csv*
"country_code"
""
""

*null.csv*
"country_code"

2. Ingest them into Rill Developer
in.csv and empty-string.csv have no rows
us.csv and null.csv import as expected

3. See this error in the terminal 
```{"level":"error","grpc.component":"server","grpc.method":"QueryDirect","grpc.method_type":"unary","grpc.service":"runtime.v1.RuntimeService","peer.address":"127.0.0.1:64324","protocol":"grpc","grpc.start_time":"2022-10-05T10:23:22-05:00","grpc.code":"Internal","grpc.error":"rpc error: code = Internal desc = json: error calling MarshalJSON for type time.Time: Time.MarshalJSON: year outside of range [0,9999]","grpc.time_ms":"0.21","message":"finished call"}```

**Expected behavior**
I should be able to import empty and arbitrary strings that don't break csv conventions.

**Comment by AdityaHegde** [comment]
Auto detection of column types seems to have changed in the new duckdb version. Values in `in.csv` are parsed as Date with infinity as value. This is the reason for time range error.

`empty-string.csv` loads without issues on the duckdb cli. Perhaps a CAPI issues.

**Comment by hamilton** [comment]
Ok ~ is this something we can fix? This sounds to me like it can be fixed but no one has gone in and learned how it's changed. Feels like a P0 for `0.13` so I think this should be prioritized.

**Comment by AdityaHegde** [comment]
This is not an issue in our app. Default duckdb behaviour has changed in current versions. @hamilton @magorlick

**Comment by hamilton** [comment]
A path to investigation:
- look at the pragmas / configuration variables in duckdb here: https://duckdb.org/docs/sql/configuration
- ask in the duckdb discord how to set these, if they aren't documented

**Comment by magorlick** [comment]
I think we need to consider the user experience regardless of where the error is. No one understands the difference between our application bugs and dependency bugs. Any error messages that clarify what has happened for users is helpful. If duckDB has had a regression I would like us to file issues and link to them from our issues so we can follow up once it is fixed instead of closing it out.  These kinds of csvs used to work and I still encounter this issue with real data files.

@hamilton , do we need to reassign someone to investigate?

**Comment by hamilton** [comment]
assigning @ericpgreen2 to investigate. Path to investigation
- recreate the issue in rill developer to build some intuition
- inquire with the duckdb team on discord
- figure out a path; either we use the csv reader table function or we set defaults with a series of `set` statements

**Comment by ericpgreen2** [comment]
Regarding `empty-string.csv`, I'm seeing the same results when I import the data in Rill as I do with DuckDB.

DuckDB:
![Image](https://user-images.githubusercontent.com/14206386/201242795-1aa8a3ec-007e-43d0-88f0-d6f258baec61.png)

Rill:
![Image](https://user-images.githubusercontent.com/14206386/201242820-8eae0172-0595-4367-bc64-013a7253e7a2.png)

**Comment by ericpgreen2** [comment]
Regarding `in.csv`, it's a mini SQL injection attack to name a table "in"! I'm guessing the problem was that you imported the CSV using the local file connector form, and for me, it's not appearing to handle upload errors correctly.

DuckDB:
![Image](https://user-images.githubusercontent.com/14206386/201243026-8d88a055-042d-43f4-9d79-c5a0d9c986c3.png)

Rill:
![Image](https://user-images.githubusercontent.com/14206386/201243122-6acec2c8-2809-472f-a2a5-07e9cd4fa7da.png)

**Comment by magorlick** [comment]
The repro steps I gave were not exactly how I found it because I encountered this in a more robust dataset I was using with country codes and a different name. If you rename the file you don't see the same error I saw when I filed this, but you do not see the string "IN".  Instead you see what Aditya describes (I believe).  A time series with infinity for the values.  :
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/5587788/201250572-34b210d5-7528-4cf5-aa8c-52ef39d39557.png">

Not a great experience, but perhaps part of the perils of ingesting CSVs with auto detected types. :) 



I am also seeing the result you show here for 3 of the 4 files where the first row is not being picked up as the header for small data sets and I am not sure why that is the case.  Are we using `header=True` in our application for data ingestion?

**Comment by nishantmonu51** [comment]
@hamilton @ericpgreen2 : Do we have clear steps on how we are going to fix this ?

**Comment by ericpgreen2** [comment]
I've lost track of what the issue is. Is it that "IN" is sometimes considered a numeric "infinity" value? Or something else?

**Comment by magorlick** [comment]
This seems like a duckDB issue in assuming CSV types. @ericpgreen2 , could you please file an issue with duckDB with an incredibly easy to reproducible test case for investigation.
