### ISSUE TITLE
filter pill menu include / exclude logic doesn't match design

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1022]
Noticing that the semantics around the filter pill menus w/ include + exclude are not what was in the design.

The filter pill menu should have the following behavior:
- when I click on an entry, it should automatically apply that filter to the dashboard. The entry should remain in the menu for the duration of the menu being open so the user has a chance to toggle the filter back on. If this isn't a good idea, I think it'd be good to add back the apply button and use that to explicitly apply.
- the include button on the bottom left of the menu should not be "apply" but instead should switch all the available menu items to whatever it's toggled to.

It appears that the include / exclude button in the menu actually is equivalent to "apply", which isn't quite right here. It needs to toggle the behavior, not serve as an affirmative action.

@magorlick @djbarnwal what do y'all think?

**Comment by magorlick** [comment]
I agree with this note.

 I would like each selection to change the dashboard in filter pills. As a user it will feel much more like "feedback with every click/keystroke". I would like the values I had selected to remain in the menu in case I want to revisit different combinations of values.  

Then it does make sense to have that include/exclude button be the toggle and feel very similar to the one in the detail tables.

**Comment by hamilton** [comment]
Moving this into `0.13`, further discussion w/ Dhiraj. This should be pretty straightforward to land I think

**Comment by bcolloran** [comment]
reopening this issue @hamilton & @djbarnwal, because I think the behavior here is still not quite right: the text label should be static; it should always just say "Exclude". By default, we want users to be in Include mode (i.e. exclude mode turned off) and to opt in to Exclude mode (as is done in the legacy product). see https://www.notion.so/rilldata/using-toggle-switch-for-exclude-b0b9033394384443870b0c32372b355b for more details

**Comment by magorlick** [comment]
@hamilton , what is the status of this work? I thought we changed it to a toggle is this still relevant?

**Comment by bcolloran** [comment]
@magorlick  -- it has been updated to a toggle, but the semantics is still wrong/confusing: the text should not change when the toggle does.

**Comment by magorlick** [comment]
Why don't we add this note to the work on improving the gestalt of include and exclude filters instead of reopening this mostly-completed issue. 
https://github.com/rilldata/rill-developer/issues/1038
