### ISSUE TITLE
Iterate on the interactions and gestalt of include/exclude filters

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1038]
(converted from a draft issue filed by @magorlick)

After having used this feature in practice for a few days, I’m noticing that the detail table and filter pills feels less intuitive to interpret than they used to be.  

- I was previously relying on whether something was selected or not to understand what I was seeing was included or excluded, however now I also have to factor in the current state of the toggle for each leaderboard in addition to the selection. This is confusing across leaderboards.

- In the filter pills I deselect things that are "X <value> and then the call to action to close and apply is "x exclude" even though I am trying to _include_ what I deselected.

- Filter pill CTA  has been updated to a toggle, but the semantics are still wrong/confusing: the text should not change when the toggle does.

**Comment by magorlick** [comment]
This feels too vague to be actionable @hamilton

**Comment by hamilton** [comment]
@magorlick this was originally an issue you filed as a draft; feel free to change the scoping here.

Additionally, we have mocks & writing for this, but haven't finished the work yet.

**Comment by magorlick** [comment]
sounds like this is enough info to be actionable and @hamilton  and @bcolloran have what they need to make progress.

**Comment by magorlick** [comment]
Notes from Mike:
- bar graphs look strange for leaderboards. Why is it so blue? Why do they often appear at 100% even when there is variance in the metrics?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5587788/199274583-9614d1c3-f384-46ac-ac0d-5fb4eba58a43.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/5587788/199274692-29b19644-20c4-4c0a-8e07-18dfc03fd91b.png">

**Comment by bcolloran** [comment]
i have mocks on the topic of lightening the bars here:
https://www.figma.com/file/wr73rSbI70HNrGNKocoBHy/Rill-Application-Design?node-id=3800%3A47752

the other issue about bar lengths is what I have been calling "rates" for shorthand in our recent conversations, but the more general issue is non-summable measures, which is far beyond the scope of this issue. I'll open another issue to track that.

**Comment by bcolloran** [comment]
I think this is fixed now as of #1236. let's file additional specific issues if we want to iterate further
