### ISSUE TITLE
Investigate reported issues with drag and drop file ingestion using docker

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1039]
Conversation from Discord after fixing this issue: https://github.com/rilldata/rill-developer/issues/738

I can't personally get docker to work using our instructions here: https://docs.rilldata.com/install/docker.  We should clean them up so they are extremely actionable and I know how to get there.

---

Marissa Gorlick — 08/16/2022
Hi ahsanshah and tombenke !  We made some fixes to our docker image.  Give it a shot when you get a chance and let us know if this resolves your issues!

ahsanshah — 08/20/2022
Hi, Thank you. I retried the docker compose option. The container runs but the web app is inaccessible.  Has this been fully tested?  Also, should I be able to load via CSV to the app? I see a DockerFile for Duck DB but this image is not referenced anywhere in the compose.

ahsanshah — 08/20/2022
Looks like the docker compose does not actually start. running "rill start" inside the container works. However, I am still unable to "drag drop" a csv file. I would assume this would work? I also dont see any demo data. Thank you.  would be great to use this in docker

Marissa Gorlick — 08/22/2022
Thanks for this feedback.  @adityahegde , do you have any thoughts on these issues?

adityahegde — 08/25/2022
Hey sorry for the delay. Can you try now?

ahsanshah — 08/25/2022
I redid the git clone and rebuild and still the same issue.  I can provide screenshots but as mentioned. No Demo data, no ability to upload CSV via drag drop. 

adityahegde — 08/25/2022
Huh. What error are you getting?

adityahegde — 08/26/2022
Also try running docker compose pull to update images. And then docker compose up --force-recreate --build -d 

ahsanshah — 08/28/2022
I retried with force recreate.  As mentioned the app comes up but 1. I dont see any sample data.  2. I am unable to load (e.g. if I drag drop a csv file it does nothing).  Also, if I go into the container directly and run rill init it errors on>:   throw err;
  ^

```

Error: Cannot find module '/app/projects/dist/cli/data-modeler-cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
} 
```
Are others able to get this compose and image to work as advertised? if so, maybe I am missing something

adityahegde — 08/29/2022
Hmmm not sure what's going on here. Can you try clearing the images?

ahsanshah — 08/29/2022
tried that. Here is the error:  Importing example datasets into the project...
```
Ecommerce...
Successfully imported /app/projects//example-assets-0.6/data/ecomm-click-stream/e-shop-clothing.csv into source e_shop_clothing
Global...
Successfully imported /app/projects//example-assets-0.6/data/global-landslide-catalog/global-landslide-catalog.csv into source global_landslide_catalog
Internet of Things...
Successfully imported /app/projects//example-assets-0.6/data/iot-env-sensor/iot-telemetry-data.csv into source iot_telemetry_data
Importing example SQL transformations into the project...
renamed '/app/projects//example-assets-0.6/models/e_shop_model.sql' -> '/app/projects//models/e_shop_model.sql'
renamed '/app/projects//example-assets-0.6/models/global_model.sql' -> '/app/projects//models/global_model.sql'
renamed '/app/projects//example-assets-0.6/models/iot_model.sql' -> '/app/projects//models/iot_model.sql'
Cleaning up the project...
renamed '/app/projects//example-assets-0.6/data' -> '/app/projects/data'
Starting example...
[Error: Catalog Error: Table with name "ts" already exists!] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR'
}
```
Server started at http://localhost:8080/
.  If it works for you then I will continue to debug on my end.  I did a complete wipe of all images, containers, and a repull.  Also, as mentioned, even if the demo doesnt work i am curious how to load new data sets? Should browser work or I need to docker cp to the file system on the container. Thanks for your help.

adityahegde — 08/29/2022
Hmmm this duckdb error might be intermittent. Are you able to run the app?
Uploading through browser will work. 

ahsanshah — 09/04/2022
nope.  When I manually try to run inside the container I get: Importing example SQL transformations into the project...
mv: target '/app/rill-developer-example/models' is not a directory.  If I create this directory and retry, it gives me TypeError: Cannot read properties of undefined (reading 'setSocketServer').  There is a separate bug for this in github as its due to the port being used. I dont believe this image works "out of the box"  but you can confirm.  What happens even when it runs is just a blank screen without any example app and uploading via browser a new CSV does not work.  Note that this is not docker running on my local its installed on a server.

ahsanshah — Yesterday at 11:54 AM
Is there any update. Tried again with the latest code base and it does not work.  If this not a working feature please let me know.

**Comment by hamilton** [comment]
@ericpgreen2 to circle back on this to see if it's fixed.

**Comment by ericpgreen2** [comment]
Closing since we've stopped supporting Docker as an install path & @magorlick has removed it from our docs.

**Comment by ahsanshah** [comment]
Hi.  Any reason why Rilldeveloper does not support Docker?  I would think this is a very flexible way to test across various OS platforms?  Will it be supported later on or the intent is to keep RillDev a tool mainly for Mac or Linux users?
