### ISSUE TITLE
WHERE statements with dates in modeling need to be CAST to a timestamp (not an issue with WASM duckDB or earlier Rill)

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1075]
The server is crashing when I use a WHERE statement with specific dates or expressions unless I cast the string to a timestamp like you have to in Druid. This didn't used to be the case.

You can see it working in duckdb using WASM here: https://shell.duckdb.org/

CREATE TABLE people(id INTEGER, date TIMESTAMP); INSERT INTO people VALUES (1, '2022-10-10'), (2, '2022-10-10');

SELECT * FROM people WHERE date = '2022-10-10'

*request to http://localhost:8081/v1/instances/36eb3b10-d8aa-4c5e-9c0c-26370261f564/query/direct failed, reason: connect ECONNREFUSED 127.0.0.1:8081*

**Comment by magorlick** [comment]
This seems to be working again.
