### ISSUE TITLE
Reduce error logs printed to the terminal

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#1081]
When I operate the application normally, particularly when writing SQL models, the application logs a bunch of SQL errors to the terminal. I've started the application via `npm run build && npm run cli -- start`

See screenshots:

![image](https://user-images.githubusercontent.com/14206386/197895378-1479f1a5-cac4-4367-890f-04b0f34b3c5d.png)

![image](https://user-images.githubusercontent.com/14206386/197895901-bfec79ca-1d67-4075-889c-d10eb306d447.png)

**Comment by ericpgreen2** [comment]
Some more errors:

![image](https://user-images.githubusercontent.com/14206386/197897070-b5cbd3a9-5b69-47fc-8776-d18026c4c6a8.png)

![image](https://user-images.githubusercontent.com/14206386/197897228-e1d521d5-84e7-483c-a69c-f57b16191ecd.png)

**Comment by AdityaHegde** [comment]
The errors posted here are from DuckDBClient where errors are caught and not logged. Perhaps it was some transient code checked in that logged the caught error. Not there in main anymore.

**Comment by ericpgreen2** [comment]
Re-opening this because I'm still seeing a bunch of logs. I've pulled version `0.13.0` and I'm running via `rill start`

**Comment by magorlick** [comment]
I agree - I still see this often.
