### ISSUE TITLE
Data imported through the CLI has a latest import date of Dec 31, 0001.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1083]
**Describe the bug**
When I import data through the CLI the latest import date is set to Dec 31, 0001 and not helpful

**To Reproduce**
1. import a data set through the `rill -import-source /path/to/file.csv` command.
2. Open the application and click on the source that was created.
3. In the workspace the date is set to Dec 31, 0001.

**Expected behavior**
I expect the time that I ran the CLI command to be the latest import date.

**Screenshots**
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/5587788/197905997-fc6a83d3-bbc8-49b6-9a04-4b38305e6552.png">

**Comment by AdityaHegde** [comment]
Cannot reproduce when imported in a fresh project. Perhaps something to do with an older project. I do not have one to debug sadly.

**Comment by hamilton** [comment]
I can easily reproduce this with a fresh project. I used the `--force` flag on a fresh install paving over an existing dataset. This should work for pretty much any dataset if you do these steps:
- import dataset with the cli using `import-source`
- force-import the same dataset with the `--force` flag
- run Rill Developer

**Comment by ericpgreen2** [comment]
I'm also seeing this bug when I import a local file through the UI.
