### ISSUE TITLE
remove npm and docker from docs

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1114]
This is a temporary fix to keep people from going down currently-existing deadends when they discover Rill Developer.

Once we've verified that docker works for users, we can add this back to the documentation.

**Comment by magorlick** [comment]
I am not convinced that WSL is working for everyone. @bcolloran , were you ever able to get it working?

**Comment by magorlick** [comment]
closed by https://github.com/rilldata/rill-developer/pull/1140

**Comment by magorlick** [comment]
moved WSL task to a new issue https://github.com/rilldata/rill-developer/issues/1143
