### ISSUE TITLE
Deleted data sources that are part of a Dashboard cause a 404 routing error.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1117]
**Describe the bug**
When I delete a data source that is powering a model-->dashboard, I get a 404 error for the dashboard instead of being taken to the metrics config with an error about the source being missing. 

**Expected behavior**
I expect to go to the metrics config with an error message that lets me know that the model is broken.

**Comment by AdityaHegde** [comment]
Same should happen when the powering source is refreshed with a different file. Have fixed this my PR as well.
