### ISSUE TITLE
 stepper 步进器不能输入小数

### ISSUE THREAD

**Issue by csshjh** [rilldata/rill-developer#1120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hamilton** [comment]
I think we should add this to `0.14`. This has come up a few times and we haven't done a good job of triaging this issue and resolving it. It's not good enough to pass blame to duckdb, since people aren't making a distinction between Rill and Duckdb in this case.

**Comment by hamilton** [comment]
Likely need a fix in the Go binding & in the frontend for this. Assigning @AdityaHegde for the Go part, and I'll tackle the frontend part as needed.
