### ISSUE TITLE
Investigate reported issues with Parquet file ingestion when the application is open

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1130]
Mike has reported this multiple times. Please validate his exact workflow from this helpful loom video.  https://rilldata.slack.com/archives/CTZ8XBQ85/p1665731835037589?thread_ts=1665723646.077609&cid=CTZ8XBQ85

**Comment by hamilton** [comment]
Someone should investigate to see if we've fixed this in the remote sources branch.

**Comment by nishantmonu51** [comment]
Link to a new video - https://www.loom.com/share/c79cc1502ddd4fb6bf989cf8f3a73f3a

**Comment by djbarnwal** [comment]
> @djbarnwal mind taking a look at this loom video to see if we fixed this in the remote sources feature release?

Can't reproduce the parquet error which was showing 0 rows when trying to import from CLI. Looks like remote sources feature fixed that one.

For the other ones in the new video should we create new issues?
