### ISSUE TITLE
The detail table for leaderboards does not have the right color during exclude filters.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1131]
**Describe the bug**
When I select the exclude filter on a detail table the colors do not invert and it is confusing to understand what was selected. I always expect included values to have a blue bar and excluded to have a grey bar.

**To Reproduce**
1. Upload a data set and create a dashboard
2. click into one of the dimensions and select a value
3. toggle to exclude.
4. notice how excluded values now appear included with a blue bar.

**Expected behavior**
excluded values should be greyed out always.

**Screenshots**
<img width="860" alt="image" src="https://user-images.githubusercontent.com/5587788/198392139-c8af8c7e-ca66-4fff-b4f0-93126403fe8a.png">

**Comment by magorlick** [comment]
Thank you for this fix @djbarnwal . The exclude toggle in the detail leaderboard is working as expected now with respect to this formatting, however I found a few critical bugs around the include/exclude functionality that also exist on main. Not sure when these were introduced, but perhaps related to recent changes?  CC @hamilton , together these bugs make the feature confusing and misleading, we should consider prioritizing fixing this for 0.14. We should probably merge in this change and file another set of issues if this was not the cause of these bugs.

https://user-images.githubusercontent.com/5587788/199518428-cfd656d3-c454-4adc-a6c2-1b6c8f8e635c.mp4

1) P0: I encountered times when I would filter things in the detail board and the metrics didn't update and were inaccurate (:06 -  :24). Could be related to including null values in the filter?  This happened intermittently.

2) P0: If you try to toggle the include/exclude in filter pills it has no effect (:24-:45) you see the toggle flip, the dashboard animates big numbers, the result set is unchanged, the detail board filters are unchanged, the detail toggle is unchanged).  This is also a problem on main, so it isn't directly related to this work.

related to:
https://github.com/rilldata/rill-developer/issues/1022
https://github.com/rilldata/rill-developer/issues/1159 -- we need to fix the labels on the toggles, it is quite confusing when they sometimes change. 
https://github.com/rilldata/rill-developer/issues/1038

**Comment by djbarnwal** [comment]
@magorlick  Thanks for the feedback. Looks like some state issue in both the cases. Would you mind approving the current open PR and filing two separate tickets for the above issues? Issue 1 looks like a state/SQL issue, @AdityaHegde can you help with that? I can pick the second one and investigate it further.

**Comment by magorlick** [comment]
here are the issues to pick up:
https://github.com/rilldata/rill-developer/issues/1185
https://github.com/rilldata/rill-developer/issues/1186
