### ISSUE TITLE
Spec: New Metrics Designer Experience

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1153]
**Issue**
A clear and concise description of the problem statement.

Specs are created to clarify the path forward to achieving our first objective of Q4. 

Spec work is informed by this proposal: https://www.notion.so/rilldata/Min-Lovable-Code-Artifacts-b5664d70a1c94defa32580747677f60f

**Comment by magorlick** [comment]
Notes from Mike on the current state:
- add button is too small for measures and dimensions
- The feedback when writing expressions hidden and we shouldn't need to hover to get feedback on what we are writing

**Comment by bcolloran** [comment]
mocks etc available at: https://www.notion.so/rilldata/0-15-Metrics-Editor-Improvements-ba1b6167323a411185bf5a18eeac4ffc
