### ISSUE TITLE
Spec CLI refactor

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1176]
See [Notion](https://www.notion.so/rilldata/CLI-experience-ce07839fcc1a4888ae78de65b7516867)

**Comment by magorlick** [comment]
Designing the CLI will require product design work and scoping.  This is not a high enough priority to consider for the immediate future and I have removed it from version 14.

**Comment by begelundmuller** [comment]
We now have an initial design [here](https://www.notion.so/rilldata/Q4-Rill-CLI-ce07839fcc1a4888ae78de65b7516867) and will be tracking the implementation [here](https://github.com/rilldata/rill-developer/issues/1190).
