### ISSUE TITLE
Detail Leaderboards have inaccurate aggregates

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1185]
*Issue*
I encountered times when I would filter things in the detail board and the metrics didn't update and were inaccurate. Could be related to including null values in the filter? This happened intermittently.

related: https://github.com/rilldata/rill-developer/issues/1131#issuecomment-1300568009

**Comment by djbarnwal** [comment]
@magorlick I am unable to reproduce this with any of my existing dashboard. Can you share the dataset which caused the error?
PS. Can't wait for shareable artifacts :D

**Comment by magorlick** [comment]
At least I can share data with you more directly through a Remote Source url! :) 

gs://scratch.rilldata.com/example-data/us_fy2022_contract.parquet

Both metrics from my video are just count(*) I believe formatted 2 ways.

**Comment by djbarnwal** [comment]
@magorlick Can we close this if this is not reproducible anymore?

**Comment by magorlick** [comment]
Yes, we can close this issue. Thank you for looking.
