### ISSUE TITLE
An empty model is created with rill init-example

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1214]
**Describe the bug**
Initializing the example should only create models for the files that are present in the directory on launch.

**To Reproduce**
1. run `rill init-example`
2. open the application
3. see an empty model called `model_0`

**Expected behavior**
The first run experience should be polished and excellent. 

**Screenshots**
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/5587788/200837402-9e5cb3a6-8869-4cba-9a23-778c551c36d0.png">

**Comment by hamilton** [comment]
I believe this has been closed out in `0.16`
