### ISSUE TITLE
Set local runtime instance ID to `local`

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#1229]
This'll help us query the runtime from the web app. Currently, we're fetching the runtime instance ID from the Node backend, but we need to transition off this approach.

Open to `local`, `default`, or any other descriptive label

**Comment by begelundmuller** [comment]
When we move to the new CLI, we've currently set it to fix the instance ID to `default`, although `local` might be a better term.

Having a fixed instance ID is convenient for e.g. doing ad-hoc calls in development, for debugging in production, or scripting for power users.

However, I think it'd be smart to write the frontend code to not rely on a fixed identifier. E.g. we might want to re-use code in the cloud or introduce multi-project local mode in the future. 

Instead, how about the following:
- You can send a request to `/local/meta` to get an object of metadata provided by the CLI. It will return the name of the instance ID (among other potentially useful metadata we might add in the future, like `pwd` or the user's name). 
- When the local app starts, it should request `/local/meta` to get the instance ID
- The instance ID should then be coordinated through a global store or passed as a parameter into the relevant sub-components

**Comment by begelundmuller** [comment]
Most of what's described above is how we ended up doing it. We went with `default` for the instance ID and `/local/config` for the metadata path.
