### ISSUE TITLE
Convert incorrectly generated mutations such as `useRuntimeServiceMetricsViewMeta` to Query

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#1233]

**Comment by begelundmuller** [comment]
By default, Orval turns `GET` requests into queries and other requests into mutations. You can manually override this behavior for a specific endpoint in `web-common/orval.config.ts` under the `api.output.override.operations` key. Here's an example for how to force it to generate a query hook for the `MetricsViewMeta` endpoint: 

```
import { defineConfig } from "orval";

export default defineConfig({
  api: {
    input: "../runtime/api/runtime.swagger.json",
    output: {
      // other options ...
      override: {
        // other options ...
        operations: {
          // LOOK HERE
          RuntimeService_MetricsViewMeta: {
            query: {
              useQuery: true,
            } 
          }
        },
      },
    },
  },
});
```

To override the generated hook for an endpoint, you need the endpoint's `operationId`, which you can find in `runtime/api/runtime.swagger.json`. The `operationId` is a unique identifier for an endpoint in OpenAPI – in the above example, it is `RuntimeService_MetricsViewMeta`.

Note that turning mutations into queries should be done with care. In some places, we decided to use `POST` requests for endpoints without side effects, such as for `MetricsViewMeta`, to allow passing complex request objects in the request body (`GET` requests cannot have a request body). But if a request has side effects, it should probably be a mutation (even if it returns data).

**Comment by begelundmuller** [comment]
As an aside, I think we should consider deprecating `useRuntimeServiceMetricsViewMeta` in favor of the generic `useRuntimeServiceGetCatalogObject` (which applies to all catalog objects, i.e. sources, models, metrics, tables). It's already generated as a query.
