### ISSUE TITLE
A dashboard with a long name breaks text wrapping in the sidebar

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#1248]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2380975/202317187-dd9c5d40-29a0-4e8a-a6e6-4780b8e04b52.png)

long names like this should be truncated with ellipses

**Comment by hamilton** [comment]
yuck, I see that we're not applying the same tailwind classes `text-ellipsis overflow-hidden whitespace-nowrap` to those. The solution should be quick; just add these to the DOM element
