### ISSUE TITLE
cannot rename a new model until it has had a valid query at least once

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#1249]
here's a weird one: it looks like you can't rename a model until that model has had a valid query at least one time. In the video below below I create a new model and attempt to edit the name; You can see that the new name is not retained when the query editor is empty, nor is it applied when I put in a gibberish string. However once I have entered a valid query in the query editor, I am able to change the name and apply the change.

note also that ".sql" appears to be appended to the name when I'm in the state where the name changes are not applied. I thought this was strange as well, because I thought that the ".sql" file extension had been removed from the app. also strange: even though ".sql"  is appended to the name, the full name including that extension is not shown, only the period is shown

https://user-images.githubusercontent.com/2380975/202318582-d898a983-d5c2-4da2-9fec-0a546c8ae46d.mp4

**Comment by AdityaHegde** [comment]
Hopefully will be fixed in the new runtime. But good to keep in mind and add tests. Thanks @bcolloran

**Comment by bcolloran** [comment]
cannot reproduce on current main, new runtime seems to have fixed this
