### ISSUE TITLE
Jarring Animation when I toggle a filter pill from "include" to "exclude"

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1257]
Switching between include / exclude causes a jarring animation: rather than keeping the chip in place and updating the element, it throws it toward the end.

This is most likely due to the API call; we have an `include` and `exclude` filter specifically.

I think we should update the API to have only `filter` and have an `type` field, which includes `include`, `exclude`, `ilike`, etc.

an alternative solution is to handle this client-side, instead opting to only update the value within the array of chips.

https://user-images.githubusercontent.com/95735/202583909-0fdcb208-3c92-43c8-b239-e43cdd9dfe1f.mp4

**Comment by AdityaHegde** [comment]
Found a simple solution to just sort the filters by name to avoid the rearrange!
