### ISSUE TITLE
Support concurrent DuckDB queries

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1316]
In DuckDB, each connection can only process one query at a time. The runtime currently opens one DuckDB connection and runs all queries sequentially on that connection. We want to add a connection pool to the DuckDB driver to enable running concurrent DuckDB queries. We should experiment with the number of concurrent connections, but something like 4 might be a good number.

DuckDB only allows one process to open a DuckDB file (for writing) at a time. But within that process, you can open multiple connections. Even though DuckDB also parallelizes the processing of each individual query, it often can't leverage all available resources all the time, so in testing we've seen performance improvements in running multiple queries on multiple connections in parallel.

We can't just naively use Go's builtin connection pool in `database/sql` for two reasons:
- DuckDB loads extensions on a connection-level, not a DB-level. So we need to run some custom init (loading the extensions) for each new connection before it's used.
- The analytical APIs use DuckDB's temporary tables, which are connection-specific. All queries related to a temporary table must run against the same connection.

-----

PR: https://github.com/rilldata/rill-developer/pull/1405

Tasks:

- [x] Parse config option `rill_pool_size` from DuckDB DSN
- [x] Support concurrent prioritized queries by using a prioritized semaphore instead of `priorityworker`
- [x] Adapt the `drivers.OLAPStore` interface to enable sequentially running multiple queries against a single connection in the pool (e.g. by adding a callback or a transaction interface)
- [x] Add a custom connection pool in the DuckDB driver that lets us load extensions before the connection is first used
- [x] Fix consistency bug described in [comment](https://github.com/rilldata/rill-developer/issues/1316#issuecomment-1357780965) below (PR: https://github.com/marcboeker/go-duckdb/pull/61)
- [x] Simplify connection pool logic by implementing https://github.com/marcboeker/go-duckdb/issues/62
- [ ] Adapt OLAP tests (`duckdb/olap_test.go`) to reflect new mechanics of priority semaphore and to test with `rill_pool_size > 1` (testing doesn't have to check performance/concurrency, just check that everything works)
- [x] Consider reserving one DB connection when `cfg.PoolSize > 1` for lightweight queries like catalog queries and dry-run queries (prepared statements)
- [x] Refactor analytical APIs that uses temporary tables to use the new single-connection interface in `drivers.OLAPStore`

**Comment by begelundmuller** [comment]
We are experiencing a bug with this PR when running an initial reconciliation against an empty DB with `rill_pool_size` > 1. This feels like a consistency bug where changes made in one DuckDB connection are not immediately reflected in other DuckDB connections.

Here's one hypothesis:
1. The DuckDB [C API docs](https://duckdb.org/docs/api/c/connect) suggest using multiple connections, so it feels like this should be supported
2. In the [go-duckdb](https://github.com/marcboeker/go-duckdb/blob/master/duckdb.go) driver, the `Open` function creates a new DB handle (using `duckdb_open`) and new connection handle (using `duckdb_connect`) each time. Maybe the use of multiple DB handles is the problem here. That should be easy to test in a temporary test case in the `go-duckdb` driver.
3. If that's the case, we should submit a patch to `go-duckdb` to re-use the same DB handle each time it opens a new connection. Fortunately, the `database/sql` interface (which the driver implements) already provides an optional mechanism to achieve this. See [`Driver` and `DriverContext`](https://pkg.go.dev/database/sql/driver#Driver) and [`Connector`](https://pkg.go.dev/database/sql/driver#Connector) in the `database/sql/driver` package.

The maintainer of go-duckdb is quite active, so we should be able to get a fix in quite fast – and until then, if relevant, we can use a [replace](https://github.com/rilldata/rill-developer/blob/3584a6ff361570495067e09852dcf2a728370688/go.mod#L153) directive in `go.mod` to use our patch.

If we fail on 2. above, we should reach out in the DuckDB Discord to ask about consistency across multiple connections.

**Comment by begelundmuller** [comment]
I'm now also realizing that we could avoid having our own custom connection pool if we used the `DriverContext` and `Connector` options (linked above) in the `go-duckdb` driver to load extensions. We could submit a PR to `go-duckdb` that lets you pass a `load_extensions=json,parquet,...` option in the DuckDB DSN, which the driver could parse to automatically load extensions on each new connection. If the submit the patch outlined above to `go-duckdb`, then this would be easy to add.

**Comment by chriszrc** [comment]
@begelundmuller so what's a reasonable number of concurrent connections to expect duckdb to handle at once now (in readonly mode)?

**Comment by domoritz** [comment]
I'm running into a similar issue where I want to use a connection pool but also have temp tables (which I think are scoped per connection). Did you find a solution to this problem?

**Comment by pjain1** [comment]
Hey @domoritz we still tie statements that use temp table to same connection using utility function, see [here](https://github.com/rilldata/rill/blob/main/runtime/drivers/olap.go#L26).
