### ISSUE TITLE
Connectivity to Azure Data Lake Storage gen2

### ISSUE THREAD

**Issue by gogi2811** [rilldata/rill-developer#1422]
**Is your feature request related to a problem? Please describe.**
I would like to to have ADLS2 as connector as well apart from S3 and GCS

**Describe the solution you'd like**
An extra tab to select ADLS2 as source and also able to select set of files apart from respective files

**Describe alternatives you've considered**
Currently I download the Parquet to local and connect

**Comment by magorlick** [comment]
Thank you for this request! We will keep your note in our backlog, however we do not have plans to expand to Azure Data Lake Storage gen2 in the short run.
