### ISSUE TITLE
if a dimension column is changed in the model, it breaks the application

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1450]
Steps to reproduce:

create this model – 
```
WITH x as (
  select 1 as value, make_date(2010,1,1) as dt, 'a' as letter
  UNION ALL select 2 as value, make_date(2010,1,2) as dt, 'b' as letter
  UNION ALL select 2 as value, make_date(2010,1,2) as dt, 'a' as letter
  UNION ALL select 3 as value, make_date(2010,1,3) as dt, 'a' as letter
  UNION ALL select 3 as value, make_date(2010,1,3) as dt, 'b' as letter
)
SELECT * from x
```

Auto-generate a dashboard

Add `EXCLUDE LETTER` to model

go back to dashboard.

I would expect to see some kind of error that the dimension no longer exists.

**Comment by ericpgreen2** [comment]
Hypothesis: we need to call "reconcile" in every +page.ts file

**Comment by AdityaHegde** [comment]
I debugged this a little. It is because we are setting errors only when yaml changes. The errors are available to the component but since yaml content didnt change it doesnt update the metrics object used in the downward components.

**Comment by hamilton** [comment]
Thanks @AdityaHegde ~ seems like we can also have a check to see if the errors need to be updated and do so accordingly.

**Comment by hamilton** [comment]
We found that this was because the model itself wasn't being invalidated in `MetricsDefWorkspace` ~ `useRuntimeServiceGetCatalogEntry`. It's possible that it's related to #1462 and in fact this model _is_ being invalidated, so if it is, we may not be able to fix it.
