### ISSUE TITLE
cannot view dashboard if i have an empty measure

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#1452]
I cannot view the dashboard if i have an empty measure in my metrics definition. I think that empty or malformed definitions should just be ignored (I thought this was the behavior previously).

screen capture of what I'm seeing-- skip to 30 seconds to see the incorrect behavior
https://user-images.githubusercontent.com/2380975/207726719-084396ec-cf4f-4095-8dec-1ce1a10d38fa.mp4

here's a link to a zip of my project folder that I seconds before I started capturing the above video https://drive.google.com/file/d/1OaoQG2k-O6oh3ocpkSXPHRnTRmeehiFI/view?usp=share_link

this is on main at commit `bb4f97e: Remove nodejs (#1358)`

**Comment by AdityaHegde** [comment]
This is intended at the moment. Any invalid measure/dimension will make the entire metric view invalid. Previously we would ignore all invalid measures and dimensions including empty ones.
