### ISSUE TITLE
time series plot component  is not correctly interpolating time grain strings where they should be

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#1453]
![image](https://user-images.githubusercontent.com/2380975/207736316-c5c09f5a-441b-45a8-97e6-a6f5a02744c1.png)

not sure exactly what is happening here, but this looks like an internal string that should be converted to a human readable string for display in the UI

**Comment by hamilton** [comment]
It may be the wrong design choice, but this is the expected behavior. The dataset is reported at the daily level, irregularly, and Rill Develop opts to show these irregular spikes instead of attempting to smooth them.

**Comment by hamilton** [comment]
Unless this is a different dataset than the UFO one

**Comment by bcolloran** [comment]
Ah, I'm not actually commenting on the content of the plot at all, I'm talking about the strings shown to describe the time grains.


I can't recall which data set that was from, it's not from the UFO data set, but here's a screenshot from the ad bid data set.

![image](https://user-images.githubusercontent.com/2380975/207748089-793a8890-ee40-4196-aad8-58a41cf944e9.png)
 
the tool tip tells me:

 "the smallest available time interval in this column appears to be at the TIME_GRAIN_MILLISECOND level"

But but that looks like a weird internal string, not a human readable string. I would expect it to say simply:

 "the smallest available time interval in this column appears to be at the millisecond level"

I assume this is just a tiny bug, but on the other hand if we are intentionally using that string rather than plain language, I would expect there to be some kind of documentation or information link that would explain why I'm seeing a term of art in this context -- when I see a technical term like that it feels like the app is trying to tell me something (it's like putting text in scare quotes), but I don't know what.

**Comment by hamilton** [comment]
got it. We're not doing that intentionally; we need human-readable versions of those, which we used to have before this migration
