### ISSUE TITLE
editing a model that has a dashboard referencing it will not save due to dependency error

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1462]
If I create the below model
```
WITH x as (
  select 1 as value, make_date(2010,1,1) as dt, 'a' as letter
  UNION ALL select 2 as value, make_date(2010,1,2) as dt, 'b' as letter
  UNION ALL select 2 as value, make_date(2010,1,2) as dt, 'a' as letter
  UNION ALL select 3 as value, make_date(2010,1,3) as dt, 'a' as letter
  UNION ALL select 3 as value, make_date(2010,1,3) as dt, 'b' as letter
)
SELECT value, dt, letter from x
```

And then create a dashboard out of this, I will see the dashboard.

If, however, I go back to the model and delete `letter` from the final select statement, and then switch to the metrics config of the dashboard:
- I will see the issue for #1450 to appear.
- BUT, if I switch back to the model, it will _not_ be updated (in other words, `letter` will reappear).

This is because we have a _dependency error_ in the model - the dashboard that relied on it now has an error.

This is a pretty big deviation from the expected user experience; we're failing fast on the model, but only for downstream catalog objects. To edit my model in any meaningful way, I'd have to start with the dashboard config and then go back to the model.

**Comment by begelundmuller** [comment]
I checked the reconciliation logic here and it's persisting the model to disk and reporting affected paths as expected. If you refresh the page after switching back to the model, you'll also see the change reflected.

This might just be a frontend cache invalidation problem. I think the culprit might be [this line](https://github.com/rilldata/rill-developer/blob/3584a6ff361570495067e09852dcf2a728370688/web-local/src/lib/components/workspace/model/ModelBody.svelte#L158) in `ModelBody.svelte`, which filters the model path out of the affected paths if there are errors, which means the model's `useRuntimeServiceGetFile` doesn't get invalidated in the subsequent call to `invalidateAfterReconcile`. @AdityaHegde, I see you added the filter [here](https://github.com/rilldata/rill-developer/commit/af81c5aa99ca657eba3ee914a1a20c4af2d7ee64#diff-aed8d5c0f0fb7cd82117df63e00e2905f119d7c62cb02bc86f2939c96a2ab834), do you think this explanation makes sense or should it get invalidated somewhere else?

**Comment by AdityaHegde** [comment]
This was needed when we were using catalog instead of file for model editor i think. It was changed in one of the PRs but not reverted here.
