### ISSUE TITLE
Develop new integer histogram API

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1473]
See [Slack discussion](https://rilldata.slack.com/archives/C04EYN66BG8/p1670460726763159) and [proposal](https://www.notion.so/rilldata/improving-integer-and-floating-point-column-profiles-bcf1e1bfb03d4ff7af73608ebb4e2c54) and [release goals](https://www.notion.so/rilldata/Integer-histogram-changes-700cd0350cad49dd9bb4e228b9590109) in Notion for context. This issue is only about implementing the backend API, not the related frontend work.

- [x] Add a task list here and socialize it (share in Slack or setup a meeting to discuss).
- [x] Pinpoint the implementation plan (see [proposal](https://www.notion.so/rilldata/improving-integer-and-floating-point-column-profiles-bcf1e1bfb03d4ff7af73608ebb4e2c54)).
- [x] Port D3.js `tickIncrement`, `nice` procedures along with unit tests.
- [x] Change Histogram API to support 2 methods.
- [x] Implement Diagnostic method using ported D3.js procedures.

**Comment by nishantmonu51** [comment]
@pjain1 : Can you help with this one?

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill-developer/pull/1719
