### ISSUE TITLE
Refactor discrepancies/duplication between column timeseries and metrics timeseries queries

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill-developer#1476]
There's some duplicated logic in these queries, which makes it harder to make changes and find bugs. We should clean things up.

- [x] Ensure null values are returned for all values in the time series (not just those that contain matching events) (e.g. by using `generate_series` and a left join)
- [x] Clarify whether we need non-single time grain units (e.g. "15 mins")

**Comment by egor-ryashin** [comment]
As discussed with Nishant, Hamilton, Benjamin - there's no plan for 15 mins (5 mins, 2 weeks and so on) time grains in the near future.

**Comment by egor-ryashin** [comment]
>Ensure null values are returned for all values in the time series (not just those that contain matching events) (e.g. by using generate_series and a left join)

FYI, it returns 0s instead of nulls as of now.
