### ISSUE TITLE
Format dates with Inter monospace

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1480]
Please format dates with monospace inter numbers like we do for the integers. The small amount of jitter on the numbers is hurting my ability to scan year from month from date.

**Comment by hamilton** [comment]
Can you point to where the jitter is happening? This may be a little tricky given that alphabet characters aren't monospace but numbers can abide by the tabular font feature. One approach would be to re-pair Inter with another monospace that isn't to opinionated, like Roboto or Hack https://twitter.com/rsms/status/1158794169986371584?s=20&t=BHPH9yaqiXAYhxtm3jySkQ

**Comment by magorlick** [comment]
Jitter was not the right word, it isn't motion. There are small pixel differences in the alignment of year-month-day that I don't like because it hurts scanability. Here I put a box around year over a column so you can better see what I am talking about.  
![image](https://user-images.githubusercontent.com/5587788/208702485-4e31845a-139c-4884-9c8c-30983fab91dd.png)

**Comment by bcolloran** [comment]
Marissa, to add a bit more context: Hamilton and I looked at using MDIO in the tables for date values, but mixing MDIO and Inter in the table looked really bad -- it wasn't really possible to get both typefaces to coexist cleanly in the table with their differences in weight and styling. As Hamilton says, unfortunately Inter doesn't have a monospaced variant that can be used to accomodate the letter characters used in the dates.

Perhaps another way of approaching the problem would be to use ISO 8601 formatting for dates, at least in a tabular contexts. Doing that would ensure that the dates always have the same width and therefore the same vertical alignment (along with the other advantages of 8601 like putting the most significant date figure first, having better sorting properties, improved density, and so on)

**Comment by hamilton** [comment]
Two options:
- right align these numbers in each cell. The number portion is monospace, so this would effectively align everything
- go with the ISO date format (and also apply to the TIMESTAMP type), which only uses numbers
