### ISSUE TITLE
Reduce space between column names and profiles in inspector

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1481]
The current default feels too wide given the more narrow lettering in Inter

**Comment by ericpgreen2** [comment]
We're using a grid layout where the column name is left-aligned and the profile charts are right-aligned, so the space in the middle is a function of how wide the inspector is, the font size, and the size of the charts. Which of those parameters do you want to change?

**Comment by ericpgreen2** [comment]
I've just submitted this PR #1504, which might address the concern.

**Comment by hamilton** [comment]
This will be addressed in #1487 by reducing the default size of the inspector
