### ISSUE TITLE
Support existing DuckDB database files

### ISSUE THREAD

**Issue by davidgasquez** [rilldata/rill-developer#153]
**Describe the solution you'd like**

When starting Rill Developer, it would be cool to have the ability to point to an existing DuckDB database that could be handled by other apps.

**Comment by magorlick** [comment]
Great idea! I will put this into our internal backlog to see where it would make sense to add to our roadmap.

**Comment by AdityaHegde** [comment]
Just a clarification. Would there be direct modifications to the database or would it be a one time import? Current assumption is that user doesnt interact with the database directly. Hence there is no periodic checks for changes in tables.

Fetching the info itself is not hard. But there is no way to easily know if an existing table changed in any sense. Perhaps we can add a button to reimport?

**Comment by hamilton** [comment]
@AdityaHegde right, I think the idea would be that on initialization of a project, you point to a db, and that db then becomes the project's db (so we set the db path to point to it). This was one of the chief reasons why I thought it was important that we listen to the db tables every once in a while in case the user changes them outside of Rill Developer. It's not very complicated to do so and it would ensure that the development experience is smooth.

**Comment by davidgasquez** [comment]
Hey there! Not sure if I'm doing something wrong. I've tried the new feature with these commands:
```
$ npm run cli --silent -- init --db /workspaces/datadex/target/local.db 
Importing tables from Duckdb database : /workspaces/datadex/target/local.db .
Make sure to close any write connections to this database before running this.
Note: Any table imports and drops will directly import/drop from this connected database.

$ npm run cli --silent -- start
Server started at http://localhost:8080
```

But, tables are not being surfaced on the UI though.
![1650539017](https://user-images.githubusercontent.com/1682202/164445041-f36649d4-f945-46d8-a8ad-8fd5fb535f4e.png)

**Comment by hamilton** [comment]
@davidgasquez hmm, did you try running `npm run build` first? We still have an annoying build step atm, but the server has changed since you pulled.

**Comment by davidgasquez** [comment]
I [re-created the image from scratch today](https://github.com/davidgasquez/datadex/blob/main/Dockerfile#L11-L12). It should've run `npm run build`.

**Comment by hamilton** [comment]
hmm. @AdityaHegde any ideas? Is there a pathing issue here in some way?

**Comment by AdityaHegde** [comment]
Was the project already initialised? Reinitialising doesnt connect to the db file as of now.

If it is a fresh project then does this query return anything?
```
SELECT table_name FROM information_schema.tables WHERE table_type NOT ILIKE '%TEMPORARY' AND table_type NOT ILIKE '%VIEW';
```

**Comment by davidgasquez** [comment]
It is a fresh project indeed. Running the query doesn't return anything. :confused: 


This is a screenshot of the commands I've executed (after a clean Docker build) and the Rill Developer state jsons. 
![1650617934](https://user-images.githubusercontent.com/1682202/164673609-04e5a161-9ae9-405a-a4a7-74eacff7033d.png)

**Comment by AdityaHegde** [comment]
Hmmm looks like init is not going through. It should have printed `You have successfully initialized a new project with Rill Developer`. Duckdb nodejs queries sometimes just quit the process without any errors. I feel like that is what is happening.

Perhaps some access issue within the docker image. How are you creating or importing tables outside of rill-developer?

**Comment by davidgasquez** [comment]
I'm creating the tables with `dbt`:

```bash
$ dbt deps
$ dbt run-operation stage_external_sources
$ dbt run
```

Both the `rill-developer` folder and the workspace one are owned by the same user, `vscode` in this case.

Happy to provide any extra log/test!

**Comment by davidgasquez** [comment]
Hey there @hamilton! I think this is due GitHub Codespaces running out of CPU/Memory when compiling DuckDB Python with extensions. I was able to replicate the error in Codespaces. 

The project should work fine locally though! I'll try to see if there is a way to make that process smoother.

**Comment by davidgasquez** [comment]
Quick update. This seems to be still an issue on `0.5.0`. You can now (thanks to Rill and DuckDB having binaries) fully repoduce things [on Codespaces in Datadex](https://github.com/davidgasquez/datadex).

**Comment by davidgasquez** [comment]
Curious if you have any news regarding this issue!

**Comment by magorlick** [comment]
> Curious if you have any news regarding this issue!

Hi @davidgasquez , I asked @AdityaHegde to take another look and he reported back that he is unable to reproduce this because we do not have the right hardware to replicate what you are seeing.

```
 > [6/7] RUN curl -s https://cdn.rilldata.com/install.sh | bash:
#0 0.557 Platform not supported: os=linux arch=aarch64
```

Unfortunately we don't have the bandwidth to investigate further in the coming weeks, but we will keep this issue open in our backlog so we can revisit when we do.

**Comment by hamilton** [comment]
Prioritizing this for 14. See #1149 for more details

**Comment by AdityaHegde** [comment]
This needs arm64 build for go runtime.

**Comment by magorlick** [comment]
Unfortunately we have decided to deprecate this feature for now. We will be revisiting how we want to include existing duckDB databases in the future with more robust support.
