### ISSUE TITLE
`rill init` wipes out existing .gitignore

### ISSUE THREAD

**Issue by gwenwindflower** [rilldata/rill-developer#1541]
**Describe the bug**
When you run `rill init` in an existing project folder you wipe out the `.gitignore` instead of appending to it, depending on your project structure bad things could then ensue, such as git trying to track your whole virtual environment.

**To Reproduce**
1. Set up a project with a .gitignore ignoring a venv or other packages folder.
2. Run `rill init` in this project.
3. Watch a babillion files suddenly get added to untracked.

**Expected behavior**
Would anticipate Rill checking for an existing .gitignore and appending to it before it opts to create a fresh one.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 17

**Comment by hamilton** [comment]
Thanks for reporting @gwenwindflower!
