### ISSUE TITLE
enable bidirectional code file updates

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1551]
Goal: when a user edits a SQL or YAML file outside of Rill Developer _while_ the application is running, it should (1) perform reconciliation and (2) update the UI.

We've decided in the interest of expediency that we'll handle this reconciliation in the frontend. As such, we'll need to implement the following:
- surface any additions to / removals from the filesystem in the navigation bar
- if a file artifact is active (i.e. a user has a model focused in the workspace) and the underlying artifact updates, a.) update the artifact in the UI and b.) perform reconciliation. We should poll the file for these changes as well.

**Comment by begelundmuller** [comment]
Notion doc is here: https://www.notion.so/rilldata/WIP-Update-code-files-bidirectionally-838773df2e3e4638ba96ded5bc14d9fb
