### ISSUE TITLE
Implement glob support for connectors

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1552]
See details in Notion ([proposal](https://www.notion.so/rilldata/WIP-Glob-support-in-cloud-connectors-93816b5766074cae829cfc5bf8f71a4a) and [tech spec](https://www.notion.so/rilldata/WIP-Glob-Support-Engineering-Tech-Spec-5dc7494c104640b2ad97e36081a4a044)). We're pursuing option 1. 

Task list:

- [x] Review and discuss proposal in Notion
- [x] Implement blob connector with glob support using [Go CDK](https://github.com/google/go-cloud)
- [x] Rewire s3 and GCS connectors to use new blob connector
- [x] Add support for `csv.delimiter` option for cloud connectors
- [x] Fix deprecated S3 auth issue
- [x] Investigate issue with `?` pattern in S3 connector
- [x] Check up on the default retry policy for file downloads. When downloading many files due to a glob, temporary network failures are likely.
- [x] Add decent unit test – basic coverage is okay (investigate if there's a good way to simulate S3 and/or GCS in a Go test)
- [x] Add docs for the new glob config options. They are: `glob.max_total_size`, `glob.max_objects_matched`, `glob.max_objects_listed`, `glob.page_size`

PRs:

- https://github.com/rilldata/rill-developer/pull/1578
- https://github.com/rilldata/rill-developer/pull/1592

**Comment by begelundmuller** [comment]
Did an experience pass on the PR, and overall things work as expected. Found some edge cases that need handling:

1. If I try to access a private S3 bucket when not authenticated, I get this error in the console. It looks like we're using a deprecated way to provide credentials (maybe this happens in `go-cloud`?). We should move to whatever is the recommended API for authenticating. Here's the error I'm seeing:
```
2023-01-10T16:03:56.621+0100	ERROR	Ingestion failed for "aws_testdata_test1" : blob (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

2. I tested globs with `**`, `*`, `{}`, and `[]` and they appear to work as expected. But I'm not able to get the `?` pattern to work – it looks like it maybe doesn't pick it up? Here's the source I'm trying:
```yaml
type: "s3"
region: "eu-north-1"
uri: "s3://begelundmuller-testdata/testcsvs/data_0?.csv"
```
and here's the error I'm getting:
```
2023-01-10T16:23:47.391+0100	ERROR	Ingestion failed for "aws_testdata_test3" : Object("testcsvs/data_0").NewReader: blob (key "testcsvs/data_0") (code=NotFound): NoSuchKey: The specified key does not exist.
	status code: 404, request id: TJHCTVM2X0Z5VST7, host id: QfatFCyu45LFBpkA5gUQnf4TfEqFGhHmCDp1MJgHqXXOMXmdZGKbmLdqe+cYd40NzkB+tDxD0SI=
```

**Comment by k-anshul** [comment]
> aws.Config.CredentialsChainVerboseErrors

From the aws sdk impl. The **deprecated** text in error message seems to be related to how error messages are reported rather than on deprecated way of authentication. There does not seem to be a way for us to configure this error messaging flag.

**Comment by k-anshul** [comment]
The cdk relies on the provider implementations to retry internally if possible (both s3 and gcs are retrying here) : https://github.com/google/go-cloud/issues/2765

**Comment by begelundmuller** [comment]
The work initially planned is done here. Follow-up work is in:

- https://github.com/rilldata/rill-developer/issues/1616
- https://github.com/rilldata/rill-developer/issues/1618
