### ISSUE TITLE
Dashboard breaks if column name ends with period

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#1564]
Facing this issue for a table which has a column named `Qty.`

<img width="926" alt="Screenshot 2023-01-04 at 9 59 18 PM" src="https://user-images.githubusercontent.com/4402679/210603052-cee8d91b-4b22-49a3-8a44-8be01e130aef.png">

**Comment by begelundmuller** [comment]
I believe this was solved in https://github.com/rilldata/rill-developer/issues/1564. Let me know if it doesn't work!
