### ISSUE TITLE
Add the global status spinner back to the application

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1567]
**Issue**
We have a regression where there is no longer a global status spinner to indicate the state of the server.  

**Importance**
This spinner is important because it helps users know if they have the right information in front of them that relates to the current query, not the prior query.

**Ask**
A spinner should be present at the top of the modeling view that spins when the server is actively processing data to surface for insights.

**Comment by hamilton** [comment]
discussed solution: add some check to the svelte query middleware that updates a "global status" store
