### ISSUE TITLE
The drag bar for modeling sometimes sticks on the screen when navigating across assets

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1571]
**Describe the bug**
On validating the experience for https://github.com/rilldata/rill-developer/pull/1561, One issue this surfaced is the drag bar for modeling between the SQL editor and the table has some weird stickiness if you navigate quickly across assets. We didn't see this in the past because the application was slower to change assets as users waited for profiles to finish.

**To Reproduce**
internal video here: https://rilldata.slack.com/archives/C04HFB0J81J/p1672930201682569?thread_ts=1672899117.870719&cid=C04HFB0J81J

**Expected behavior**
I don't expect the pull bar to follow me around the application. :)

**Comment by djbarnwal** [comment]
@magorlick Can't access the internal video as it might be in a private dm/channel. I tried moving between assets and moving the drag bar but I am unable to reproduce this bug. Can you check if it's still reproducible?

**Comment by magorlick** [comment]
Let's close this for now. We probably had an uncaught error when we migrated that caused this that we have fixed. If we see it again, we will refile. Thank you!
