### ISSUE TITLE
The runtime doesn't put escape quotes around model names when creating views.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1576]
**Describe the bug**
The runtime doesn't put escape quotes around model names when creating views. This can create errors when you use reserved words in the model name.

**To Reproduce**
1. Create a new model
2. Name is cast.sql
3. run rill start
4. See error during rehydration

**Expected behavior**

**Screenshots**
<img width="822" alt="image" src="https://user-images.githubusercontent.com/5587788/211096011-770d1611-8f83-4571-b368-ecc65c532d2c.png">

**Comment by rakeshsharma14317** [comment]
@magorlick Do we need to support reserve or any such keywords for models? for the temporary fix added the changes, this will not error while renaming and reconcile, 

Added few details here [https://github.com/rilldata/rill-developer/pull/1631#issue-1538160557](https://github.com/rilldata/rill-developer/pull/1631#issue-1538160557)
