### ISSUE TITLE
Source ingestion error messages do not wrap in UI

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1589]
**Describe the bug**

During testing of glob support, I tried to run a glob pattern targeting files with different schemas. The error message exceeded the size of my screen and did not wrap.

**Screenshots**

<img width="1792" alt="Screenshot 2023-01-10 at 15 36 25" src="https://user-images.githubusercontent.com/791356/211604505-0ab02f26-e2af-4251-8020-ae7c021b9b25.png">

**Comment by hamilton** [comment]
thanks for reporting ~ this looks like a regression.
