### ISSUE TITLE
Data set ingestion causes Runtime panic

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#1594]
**Describe the bug**
Two public data sets I try to ingest into Rill Developer cause a runtime panic and I don't know why.

**To Reproduce**
1. try to ingest one of these two files in the remote sources modal

- FROM "s3://aws-roda-hcls-datalake/binding_db/article_kword/part-00000-826a7668-edc0-4c90-a2ea-e16fa42dd3b1-c000.snappy.parquet”

- FROM “s3://aws-roda-hcls-datalake/binding_db/monomer/part-00000-19d0a400-19f2-40d3-9934-a325f767137e-c000.snappy.parquet”

2. See long runtime panic error in terminal and nothing in the application.

**Expected behavior**
Data should be ingested if there are no errors in the format. If there are errors, we should display them in the application for the user to troubleshoot in a human-readable way.

**Comment by k-anshul** [comment]
May be unrelated to this issue but we also need to build support for access to anonymous/public buckets. Currently by default aws sdk seems to be loading credentials or complaining that credentials are not provided. 
https://github.com/aws/aws-sdk-go/issues/205

**Comment by magorlick** [comment]
@AdityaHegde had the same problem with this data and I did not. I had to manually download it and send it to him. Is it related to your IP address and country-specific differences in how this works as a "public" dataset? Not really sure..

**Comment by rakeshsharma14317** [comment]
After debugging we found that issue is from duckdb, 
Reported the bug on Duckdb -> [https://github.com/duckdb/duckdb/issues/5975](https://github.com/duckdb/duckdb/issues/5975)

Will update the status once we get the response from duckdb

**Comment by magorlick** [comment]
> After debugging we found that issue is from duckdb, Reported the bug on Duckdb -> [duckdb/duckdb#5975](https://github.com/duckdb/duckdb/issues/5975)
> 
> Will update the status once we get the response from duckdb

Thank you! Any insight into the "public" nature of this data set being inaccessible to several folks?

**Comment by magorlick** [comment]
The issue described here is on the duckDB side and will be fixed in the next release. We are going to make another issue to cover the support for access to anon lookup.
