### ISSUE TITLE
Do Rill Support Azure Blob Storage

### ISSUE THREAD

**Issue by akash-goel** [rilldata/rill-developer#1641]
Hi Team,

we would like to check do Rill Support Azure Blob Storage.

if would like to add more features than is there example project or document for it which we can refer.

Regards,
Akash

**Comment by magorlick** [comment]
Hi @akash-goel ! 

Unfortunately we don't currently support Azure Blob Storage. 

You can check out more about our supported data sources at https://docs.rilldata.com/using-rill/import-data and follow a quick start example at https://docs.rilldata.com/quick-start.
