### ISSUE TITLE
Comments in model are not being preserved in the UI

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#1660]
**Describe the bug**
Comments added to SQL in model are not being preserved in the UI

**To Reproduce**
1. Create two models A and B
2. Add comment to model A 
3. Switch to model B
4. Switch back to model A

**Screenshots**

https://user-images.githubusercontent.com/4402679/215078448-0a14ab8a-d537-463e-bd56-bcc0fa1019f8.mp4

**Comment by magorlick** [comment]
I am also encountering this and it is hurting our ability to use the v1 materialization work that @begelundmuller put together for 0.20.  Repro steps:

1. Create a model with a dashboard. I can see this with my public example here: https://github.com/magorlick/nypd-complaints
2. Add comment to your model at the top indicating you want to materialize the file `-- @materialize:true`
3. Navigate to the dashboard
4. Navigate back to the model and the comment is mostly or entirely missing.

@hamilton @AdityaHegde , can we please make this fix a P0? It would be nice to fix this before the .20 release for story telling.

**Comment by AdityaHegde** [comment]
The comment is only missing in the UI, because the request to get model sql is not invalidated. It is persisted into the file system and the database.
