### ISSUE TITLE
Install script doesn't do anything when TLS verification fails

### ISSUE THREAD

**Issue by ganius** [rilldata/rill-developer#1665]
The bash install script on the quick start page doesn't do anything when the curl TLS verification fails. This usually happens in corporate networks that use custom certificates or proxies. 

`curl -s https://cdn.rilldata.com/install.sh | bash`

This behaviour may be hard **To Reproduce** but the steps I took:
1. Be in a corporate network with custom certificates not signed by any CA
2. Open up a Linux bash shell
3. Copy, paste and run the installation script above, which is taken from the **Install Rill** page: https://docs.rilldata.com/using-rill/install 
4. When the VERSION is the latest, which is the default, the curl command tries to retrieve the latest URL but fails because of the failed verification. However, this command has the `--silent` flag. Therefore the script abruptly ends without any output or error messages and without doing anything.

**Expected behaviour**
I would have expected the error message from the curl command itself so that I could take the proper action.

**Desktop:**
 - OS: [Ubuntu 22.04.1 LTS]
 - Terminal: bash

**Additional context**
Removing the `--silent` flag can be an option. Alternatively, adding error handling to that step would help capture common installation failures such as this one and guide users to potential solutions at their own discretion.

In my case, I solved the problem by copying the script and adding the `--insecure` [(or -k) flag](https://curl.se/docs/manpage.html#-k) to all curl commands.

**Comment by magorlick** [comment]
Thank you for reporting @ganius , I really appreciate these excellent repro steps.  We will take a look for the next release.

**Comment by magorlick** [comment]
Adding a note to our documentation
