### ISSUE TITLE
Couldn't pass beyond "npm run build"

### ISSUE THREAD

**Issue by kuatroka** [rilldata/rill-developer#168]
**Describe the bug**
Sorry I can't describe it in full. A bit pressed for time, but the gist is you need to polish the install procedure. I tried it on 
Windows 10 with Node 16 and it complained about the backslashes

```
$ npm run build

> rill-developer@0.1.0 build
> ./build-tools/build.sh && tsc --project tsconfig.node.json

'.' is not recognized as an internal or external command,
operable program or batch file.
```
I then changed the erroring lines manually in the `package.json` to the Windows way like so

```
"build": "./build-tools/build.sh && tsc --project tsconfig.node.json",
"prepack": "./build-tools/replace_package_type.sh module commonjs",
"postpack": "./build-tools/replace_package_type.sh commonjs module",
```
But it still didn't like it and this time there were no error message at all, just this.
```
> rill-developer@0.1.0 build
> .\build-tools\build.sh && tsc --project tsconfig.node.json
```

I have also tried to install it in a docker container based on alpine linux, but it gave me other host of errors.

Cheers.

**Comment by hamilton** [comment]
Thanks for reporting @kuatroka!

**Comment by hamilton** [comment]
Could you run `npx svelte-kit build` instead of `npm run build` and see what the errors are? Seems like suppressing all the output around building is not actually that helpful.

**Comment by kuatroka** [comment]
Below is all the output I got after running `npx svelte-kit build`
I can't seem to be able to format it better

<details>

$ npx svelte-kit build
vite v2.7.6 building for production...
transforming (112) src\lib\components\column-profile\utils.ts
warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.    
warn - Update your configuration file to eliminate this warning.
warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources
transforming (402) src\common\priority-action-queue\Heap.ts18:52:45 [vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte 
components from a package, then please contact the author and ask them to export the package.json file.
- d3-format
- @codemirror/view       
- @codemirror/rangeset   
- @codemirror/commands   
- @codemirror/state      
- @codemirror/basic-setup
- @codemirror/lang-sql   
- @codemirror/text
- @codemirror/matchbrackets
- @codemirror/language
- @lezer/common
- style-mod
- w3c-keyname
- @codemirror/history
- @codemirror/fold
- @codemirror/gutter
- @codemirror/closebrackets
- @codemirror/search
- @codemirror/autocomplete
- @codemirror/comment
- @codemirror/rectangular-selection
- @codemirror/highlight
- @codemirror/lint
- @lezer/lr
- d3-scale
- d3-time-format
- @codemirror/panel
- crelt
- @codemirror/tooltip
- d3-array
- d3-time
- d3-interpolate
- internmap
- socket.io-parser
- d3-color
- engine.io-parser
✓ 402 modules transformed.
.svelte-kit/output/client/_app/manifest.json                                          8.55 KiB
.svelte-kit/output/client/_app/pages/__layout.svelte-3a5348f9.js                      6.64 KiB / gzip: 2.72 KiB       
.svelte-kit/output/client/_app/error.svelte-21b4a1c5.js                               1.56 KiB / gzip: 0.75 KiB       
.svelte-kit/output/client/_app/pages/dev/__layout.svelte-381ac64f.js                  0.77 KiB / gzip: 0.50 KiB
.svelte-kit/output/client/_app/pages/dev/metrics-cube-experiment.svelte-2c0e79e9.js   5.37 KiB / gzip: 1.81 KiB       
.svelte-kit/output/client/_app/start-6486c961.js                                      23.40 KiB / gzip: 7.62 KiB      
.svelte-kit/output/client/_app/pages/dev/source-gallery.svelte-ce1f0bb9.js            4.17 KiB / gzip: 1.92 KiB       
.svelte-kit/output/client/_app/pages/dev/sidebar-icons.svelte-dabac2af.js             2.22 KiB / gzip: 0.92 KiB       
.svelte-kit/output/client/_app/pages/dev/sql-traverse.svelte-0f8f2583.js              3.73 KiB / gzip: 1.90 KiB       
.svelte-kit/output/client/_app/pages/dev/data-types.svelte-3e0351e6.js                3.48 KiB / gzip: 1.46 KiB       
.svelte-kit/output/client/_app/pages/dev/components.svelte-4e56bd62.js                13.55 KiB / gzip: 5.32 KiB      
.svelte-kit/output/client/_app/pages/dev/tooltips.svelte-c05ebd2c.js                  12.36 KiB / gzip: 4.46 KiB      
.svelte-kit/output/client/_app/pages/dev/parse-demo.svelte-fc3a8cef.js                16.57 KiB / gzip: 4.93 KiB      
.svelte-kit/output/client/_app/pages/dev/float.svelte-bb422e20.js                     6.08 KiB / gzip: 2.24 KiB       
.svelte-kit/output/client/_app/chunks/index-6a16fe31.js                               0.53 KiB / gzip: 0.34 KiB       
.svelte-kit/output/client/_app/pages/dev/columns.svelte-ca2aec2f.js                   10.67 KiB / gzip: 4.45 KiB      
.svelte-kit/output/client/_app/chunks/guid-5b32b27b.js                                0.16 KiB / gzip: 0.13 KiB       
.svelte-kit/output/client/_app/chunks/app-store-c6a18385.js                           17.03 KiB / gzip: 4.78 KiB      
.svelte-kit/output/client/_app/chunks/SurfaceView-30262eaf.js                         3.57 KiB / gzip: 1.48 KiB       
.svelte-kit/output/client/_app/chunks/Editor-c524b4f1.js                              2.60 KiB / gzip: 1.37 KiB       
.svelte-kit/output/client/_app/chunks/MenuItem-3b4b5941.js                            4.60 KiB / gzip: 2.15 KiB       
.svelte-kit/output/client/_app/chunks/TooltipContent-1987e504.js                      8.20 KiB / gzip: 3.32 KiB       
.svelte-kit/output/client/_app/chunks/duckdb-data-types-99162c7a.js                   1.31 KiB / gzip: 0.64 KiB       
.svelte-kit/output/client/_app/chunks/SmallHistogram-5de422a9.js                      1.06 KiB / gzip: 0.58 KiB       
.svelte-kit/output/client/_app/assets/start-d5b4de3e.css                              0.19 KiB / gzip: 0.16 KiB       
.svelte-kit/output/client/_app/assets/MenuItem-0947c967.css                           0.36 KiB / gzip: 0.16 KiB
.svelte-kit/output/client/_app/chunks/Parquet-6104291d.js                             19.72 KiB / gzip: 7.14 KiB      
.svelte-kit/output/client/_app/assets/sort-utils-6774ee2f.css                         0.87 KiB / gzip: 0.38 KiB       
.svelte-kit/output/client/_app/assets/pages/dev/components.svelte-c049671e.css        0.26 KiB / gzip: 0.14 KiB       
.svelte-kit/output/client/_app/chunks/DataTypeIcon-fd5211dc.js                        19.47 KiB / gzip: 5.90 KiB      
.svelte-kit/output/client/_app/chunks/NumericHistogram-d825e4c4.js                    10.85 KiB / gzip: 4.36 KiB      
.svelte-kit/output/client/_app/assets/Editor-40301701.css                             0.14 KiB / gzip: 0.13 KiB       
.svelte-kit/output/client/_app/assets/pages/index.svelte-103c8ed4.css                 1.55 KiB / gzip: 0.48 KiB       
.svelte-kit/output/client/_app/assets/pages/dev/source-gallery.svelte-a1a9dd76.css    0.15 KiB / gzip: 0.13 KiB       
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-8c14e4b8.css              26.04 KiB / gzip: 5.46 KiB      
.svelte-kit/output/client/_app/chunks/sort-utils-31ffd1bd.js                          59.83 KiB / gzip: 15.60 KiB     
.svelte-kit/output/client/_app/pages/index.svelte-da816e1b.js                         101.42 KiB / gzip: 27.05 KiB    
.svelte-kit/output/client/_app/chunks/vendor-07de596a.js                              441.90 KiB / gzip: 147.30 KiB   
vite v2.7.6 building SSR bundle for production...
transforming (165) src\lib\components\table\Table.svelte18:52:48 [vite-plugin-svelte] The following packages did not export their `package.json` file so we could not check the "svelte" field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- @codemirror/view
- @codemirror/commands
- @codemirror/state
- @codemirror/basic-setup
- d3-format
- @codemirror/lang-sql
- @codemirror/rangeset
- d3-time-format
- d3-scale
✓ 181 modules transformed.
.svelte-kit/output/server/app.js                                                      0.09 KiB
.svelte-kit/output/server/chunks/app-451c4fbe.js                                      21.09 KiB
.svelte-kit/output/server/chunks/__layout-9242d1ed.js                                 4.97 KiB
.svelte-kit/output/server/chunks/app-store-07dc9c1b.js                                32.02 KiB
.svelte-kit/output/server/chunks/index-cb5c37bb.js                                    1.07 KiB
.svelte-kit/output/server/chunks/index-e9c3fc58.js                                    2.24 KiB
.svelte-kit/output/server/chunks/guid-5b32b27b.js                                     0.24 KiB
.svelte-kit/output/server/chunks/error-fc427ba8.js                                    0.74 KiB
.svelte-kit/output/server/chunks/index-0607644d.js                                    60.78 KiB
.svelte-kit/output/server/chunks/SurfaceView-f22a1634.js                              4.23 KiB
.svelte-kit/output/server/chunks/TooltipContent-ff91b2d9.js                           7.31 KiB
.svelte-kit/output/server/chunks/Parquet-98385b13.js                                  10.73 KiB
.svelte-kit/output/server/chunks/sort-utils-13eb9d13.js                               40.34 KiB
.svelte-kit/output/server/chunks/MenuItem.svelte_svelte_type_style_lang-0ed28cd2.js   0.43 KiB
.svelte-kit/output/server/chunks/index-a7585f7c.js                                    3.01 KiB
.svelte-kit/output/server/chunks/Editor-c0b9078a.js                                   3.02 KiB
.svelte-kit/output/server/chunks/duckdb-data-types-3574c8d3.js                        1.76 KiB
.svelte-kit/output/server/chunks/DataTypeIcon-14b6bb36.js                             17.22 KiB
.svelte-kit/output/server/chunks/SmallHistogram-8d406549.js                           1.29 KiB
.svelte-kit/output/server/chunks/NumericHistogram-05f0c4ce.js                         9.95 KiB
.svelte-kit/output/server/chunks/__layout-588abdfd.js                                 0.38 KiB
.svelte-kit/output/server/chunks/metrics-cube-experiment-eb07fb4f.js                  1.87 KiB
.svelte-kit/output/server/chunks/source-gallery-4a38359f.js                           2.92 KiB
.svelte-kit/output/server/chunks/sidebar-icons-ac0320cd.js                            1.09 KiB
.svelte-kit/output/server/chunks/sql-traverse-d26579bc.js                             4.27 KiB
.svelte-kit/output/server/chunks/components-b8fd4425.js                               11.04 KiB
.svelte-kit/output/server/chunks/data-types-763e54db.js                               2.74 KiB
.svelte-kit/output/server/chunks/parse-demo-61ff9845.js                               12.98 KiB
.svelte-kit/output/server/chunks/tooltips-c655813d.js                                 8.54 KiB
.svelte-kit/output/server/chunks/columns-06772e84.js                                  6.21 KiB
.svelte-kit/output/server/chunks/float-6fa6853e.js                                    6.40 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static

  ✔ done


</details>


After running `npm run preview` ,it tells me

```
$ npm run preview

> rill-developer@0.1.0 preview
> svelte-kit preview

Port 3000 is occupied
Terminate the process occupying the port or specify a different port with --port
```
even though noting is running on 3000. When I run  `npm run preview --port 5500`
it still doesn't work and gives me the error about the port 3000 

```
$ npm run preview --port 5500

> rill-developer@0.1.0 preview
> svelte-kit preview "5500"

Port 3000 is occupied
Terminate the process occupying the port or specify a different port with --port
```

I think the best option would be for you to dockerise the app so everyone would download or build (Dockerfile or docker-compose up) the same app set up

Cheers

**Comment by hamilton** [comment]
@kuatroka agreed ~ in fact we have a WIP PR to dockerize. We should really have this work on windows machines, however. It's unclear why it won't run as-is, given that we're not doing anything clever with svelte / sveltekit, and it normally runs on windows, so we'll investigate to see if we can reproduce.

**Comment by kuatroka** [comment]
Sorry I can't be of any help here. I have no slightest clue about how front-end frameworks work. I'm a python beginner and I'm building a data centric app. I just saw the reference to your product on twitter and thought to check how this new (for me) duckDB works. This is how I ended up in this rabbit hole of the svelte installation. I can't be of help here, but I'll be happy to test when the container is ready. Cheers

**Comment by kuatroka** [comment]
btw, these are the warnings I when running `npm install`. I don't know if these are critical or not.

```
$ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142   
```

**Comment by hamilton** [comment]
@kuatroka no worries :) @bcolloran mind taking a look since you have a windows machine?

**Comment by kuatroka** [comment]
I tried to run` docker-compose up `on the latest build.

![image](https://user-images.githubusercontent.com/9093546/165756944-b3677ce0-f18d-48d4-870c-da86c9600de3.png)

**Comment by hamilton** [comment]
@kuatroka this is helpful, thanks. We'll unwind this build script we're using since it's not really necessary.

**Comment by bcolloran** [comment]
We now have other problems on windows, but this issue is no longer relevant -- much of this code has been replaced already.
