### ISSUE TITLE
Add new time grain and time range configs to dashboard YAML

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1680]
For metrics views (dashboards), we currently support passing a list of `time_grains`. We want to support more configurability here:

- [ ] Change the `MetricsView.time_grains` proto to use the `TimeGrain` enum instead of strings (and change frontend accordingly). It might make sense to move the `TimeGrain` enum into the `catalog.proto` file.
- [ ] Add a `default_time_grain` key in YAML and the internal representation
- [ ] Add a `default_time_range` key in YAML and the internal representation. It should support setting a recency interval (e.g. "10 days") or "all time".
  - Before building this, please suggest some ideas for what the YAML and internal representation could look like. 

Resources:
- The internal representation of metrics views are defined in `proto/rill/runtime/v1/catalog.proto`
- The logic parsing YAML into internal representation is in `services/catalog/artifacts/yaml`

**Comment by djbarnwal** [comment]
#1704 is related

**Comment by pjain1** [comment]
First 3 items need to be done here - https://github.com/rilldata/rill-developer/issues/1704

**Comment by pjain1** [comment]
@begelundmuller have few questions -
1. In object.go we have intermediate representation of artifacts like MetricsView etc. is it because yaml.Unmarshal and yaml.Marshal does not work on proto structs and expects all the fields to be simple like strings, bools etc.
2. `default_time_grain` is already present in yaml and internal object but I think it will be needed in proto message as well.
3. For representing default_time_range we already one enum named TimeRangeName in api.proto, I believe we can use that in proto message. For yaml we can predefine strings to be used like 10 days, 1 day, 6 hours since its free form it might be good to give suggestions here in the sql editor and also fail validation if its not correct. Other way is to use ISO 8601 representation like P10D , P6H etc. but then user can write any arbitrary duration here. Actually same goes for time grain as well, how does user know the acceptable values.

**Comment by begelundmuller** [comment]
1. It's a good question. Currently, the mapping is close to 1-to-1, but that might not always be the case. The internal representation may be more explicit. E.g. in YAML, we might put `sample: 10 MB` and in internal representation it would be something like `{sample: {strategy: head, bytes: 10000000}}`. In future, we might also add more code file compilers (like SQL in addition to YAML), but the internal representation should stay the same. I think of it a bit like the difference between an AST type and a logical type in SQL. 
  - Side note: the current YAML parsing and mapping to internal representation is slightly confusing now (the `copier` is a bit too much magic IMO), but let's not touch that now – we can tackle it when improving reconcile
2. Good catch, not surprised if some of this logic is halfway there
3. Good observation. We haven't given much thought to this previously, but it would be good to solve this the right way (@nishantmonu51 agrees). I like the idea of using the ISO 8601, and then the frontend can map it up to nice names to guide the user (if the user overwrote the YAML with a custom range, we could just show "custom range" in the UI). (Invalid grains or ranges should return an error when parsing the YAML.)

I thought some more about time ranges in general. For a flexible design, we would need to support:
- All time
- All time until T
- All time after T
- T +/- offset
- current time +/- offset

The ISO 8601 spec has a section on [time intervals](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) that appears useful. For example, we could slightly extend it to do something like:

```yaml
default_time_range: / # all time
default_time_range: 2020-01-01/2021-01-01 # 1st Jan 2020 to 2021
default_time_range: /2021-01-01 # all time until 1st Jan 2021
default_time_range: P-30D # last 30 days relative to now() at eval time
default_time_range: P30D/2020-01-01T00:00:00Z // 30 days lead up to 1st Jan 2020
...
```

For the internal representation, we would have some different options:

```proto3
// Option 1
string default_time_range = 1;

// Option 2
message TimeRange {
  google.protobuf.Timestamp start_time = 1; // nil means since all time
  google.protobuf.Timestamp end_time = 2; // nil means until all time
  string offset_duration = 3;
}
TimeRange default_time_range = 1;

// Option 3
message TimeRange {
  google.protobuf.Timestamp start_time = 1; // nil means since all time
  google.protobuf.Timestamp end_time = 2; // nil means until all time
  int64 year_offset = 3;
  int64 month_offset = 4;
  int64 week_offset = 5;
  int64 day_offset = 6;
  int64 hour_offset = 7;
  int64 minute_offset = 8;
  int64 second_offset = 9;
}
TimeRange default_time_range = 1;
```

There are probably some trade-offs on how the UI would consume these. Some of this might also be useful in other places.

Just some thoughts, let me know what you think.

**Comment by pjain1** [comment]
> In the UI, if the user manually specifies a non-standard interval in the YAML, it could just show it outright or label it "custom".

What do you mean by non-standard here, can you give some examples ? do you mean users will still write last 1 day, last hour etc. but internally we store it in ISO 8601 format ? and by custom you mean if user wrote something other than the list of time ranges we support in string format ?

Also for your first answer, my main confusion is the difference between internal representation and corresponding proto object. For example we have MetricsView struct in objects.go and MetricsView message in catalog.proto. So I was wondering if we can directly create proto object from yaml and vice versa and remove intermediate structs. That can still support explicit representation you mentioned, this is more for my understanding.

**Comment by pjain1** [comment]
More clarification from @begelundmuller 
>  I think in UI they will probably do a drop-down with a few preset options (probably like the enum you highlighted). But then UI should write that into the YAML as ISO 8601. If the user then edits the YAML to an ISO value not supported in the drop-down, it’s fine, it could just say “custom” or the ISO value directly or something like that
