### ISSUE TITLE
Can we get OS based binaries like tadviewer?

### ISSUE THREAD

**Issue by AshishKapoor** [rilldata/rill-developer#169]
**Is your feature request related to a problem? Please describe.**
For end-users/consumers, it'd be easier to simply get up and running with it.

**Describe the solution you'd like**
Being an electron app ecosystem, it should be possible.

**Describe alternatives you've considered**
Ref: https://www.tadviewer.com/ they offer OS-based binaries.

**Additional context**
NA

**Comment by hamilton** [comment]
Hi @AshishKapoor! Yes, we'll likely have some solution to this problem at some point. Until then, we're likely to experiment with making basic installation with a CLI easier first.

**Comment by hamilton** [comment]
I believe this is going to hit for `0.9` (this week) more definitively. Sorry this took so long!
