### ISSUE TITLE
Runtime: Add JWT parsing and simple authorization

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1690]
As part of our work on a hosted version of Rill, we'll need a way to authorize requests made to the runtime. We will probably do authentication and JWT issuance through the control plane, but the runtime will need the ability to parse and validate JWTs. We also need the ability to set various permissions inside the JWTs, which are checked in the API resolvers.

Task list:

- [x] Add runtime config key for a JWT secret. If no secret is configured, it should ignore JWTs.
- [x] Add middleware for extracting and parsing JWTs from authorization headers (note: due to using `grpc` through `grpc-gateway`, this might look slightly different than for a REST server)
- [x] In middleware, extract payload from the JWT and add it to the request `ctx`
- [x] Add helper functions for getting the JWT payload from the `ctx` in request handlers
- [x] Prototype simple authorization by parsing an `instance_id` key from the JWT payload. If it's set, requests to other instances should be rejected.

**Comment by pjain1** [comment]
Here's a starting point - https://github.com/rilldata/rill-developer/pull/1728. Its for getting initial feedback. There are couple of points for discussion -
1. We will need to add an http handler as well similar to the grpc interceptors to authenticate http only requests.
2. We might consider using RSA based signing method to sign JWTs. We can use JWK for storing public key used to sign the token or retrieve it from well known endpoint of the auth provider and cache it. Thus we don't have to manage any `secret` used in case of symmetric algo like HMAC.
3. For enabling-disabling auth we can check if keyId is set or not in the config. This keyId points to a key in JWK. If key Id is not present in the config then we don't set the auth interceptors, handler.

Any other observations, points to discuss ?

**Comment by begelundmuller** [comment]
> 1. We will need to add an http handler as well similar to the grpc interceptors to authenticate http only requests.

We can skip this for now. The runtime server only has two non-proto endpoints right now, and we don't need those in the hosted version.

> 2. We might consider using RSA based signing method to sign JWTs. We can use JWK for storing public key used to sign the token or retrieve it from well known endpoint of the auth provider and cache it. Thus we don't have to manage any `secret` used in case of symmetric algo like HMAC.

Sounds good to me, don't have a strong opinion here. What do others do/recommend?

> 3. For enabling-disabling auth we can check if keyId is set or not in the config. This keyId points to a key in JWK. If key Id is not present in the config then we don't set the auth interceptors, handler.

That's what I initially thought as well. On reflection, to prevent accidentally making everything public if a key is not set, we should probably have a separate config key for auth and the secret.

The config should be set on the runtime or runtime server object, then loaded and assigned from env variables here: https://github.com/rilldata/rill-developer/blob/main/cli/cmd/runtime/start.go
