### ISSUE TITLE
for "all time", time series API tends to generate one extra point at the end of the series

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1734]
It appears somewhere in the pipeline, we're adding a day. IT coudl be in the API, or it could be somewhere in the dashboard code.

**Comment by begelundmuller** [comment]
Backend work is resolved here: https://github.com/rilldata/rill-developer/pull/1757

**Comment by begelundmuller** [comment]
According to Eric, this doesn't require further frontend work.
