### ISSUE TITLE
Runtime: Support instance-level env config and injection in sources YAML through Go templates

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1743]
- [x] Add a `--env KEY=VALUE` support in CLI
- [x] Also support loading env var default values from `rill.yaml`
- [x] Add [Go templates](https://pkg.go.dev/text/template) for SQL and YAML loaders – exposing access to env variables
- [x] Use instance-level env vars in connectors when relevant
- [x] Add flag for disabling use of host environment variables in connectors

**Comment by k-anshul** [comment]
Some open questions :
1. How would the user pass environment variables in the cli ? via some existing command or we need to introduce some new command. 
2. I am assuming that rill.yaml env variables will always be global and not specific to any instance
3. Where do we want to store the state of env variables somewhere ? in some metadata ?
4. Do we plan to expose instance-level env variables the the users or will they remain completely hidden from users ?

**Comment by begelundmuller** [comment]
1. I'm picturing something like `rill start --env KEY=VALUE`, and then we set those values on the `"default"` instance that gets created when running `rill start`
2. Actually, the `rill.yaml` is not global, but specific to a project (it comes alongside the code files, [see example here](https://github.com/rilldata/rill-developer/tree/main/examples/default)). So when a project is reconciled, if the `rill.yaml` specifies any env values, they should be set on the instance that is getting reconciled.
3. Yes, we should store it in the [registry](runtime/drivers/registry.go) – maybe just as a list field? For the hosted version, the registry will be backed by a persistent datastore. Some of its contents should go in Vault for security at some point, but that's not needed for now.
4. No they should be completely hidden from the user. This is just for resolving "building" the code files and running connectors.

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill-developer/pull/1784
