### ISSUE TITLE
Export should offer to download CSV/parquet, not write it to disk

### ISSUE THREAD

**Issue by wlach** [rilldata/rill-developer#175]
**Is your feature request related to a problem? Please describe.**

Export currently just writes CSV/parquet files to disk in a path I can't remember (the tooltip disappeared before I could note down where it went: `rill-developer/export/query_0.csv`). It would be far more convenient if I could choose where the files get downloaded.

**Describe the solution you'd like**

Pop up file chooser, write to Downloads folder or wherever else. This also opens up the possibility of opening the result in Excel.

**Describe alternatives you've considered**
N/A

**Comment by hamilton** [comment]
great point!
