### ISSUE TITLE
implement minimum timegrain in metrics configuration

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#1766]
We've taken a moment to reconsider the work needed for configurable time defaults for `0.22`, and decided to change our approach. We'll keep the default timerange, but
1. we'll remove the default time grain & available timegrain options
2. we'll add a minimum time grain option

cc @djbarnwal for awareness

**Comment by begelundmuller** [comment]
What should the field name be? We could do something like `min_time_grain`, `minimum_time_grain`, `smallest_time_grain`, `lowest_time_grain`, etc.

But on reflection, assuming “grain” means “granularity” (interestingly, that connection is not in the built-in dictionary on Mac), maybe it should just be `time_grain` or `time_granularity`? You could argue “minimum” is implied – the definition of “granularity” is “the scale or level of detail in a set of data”.

**Comment by begelundmuller** [comment]
(FYI the change is easy to make – we'll just revisit https://github.com/rilldata/rill-developer/pull/1722/files and change where relevant.)

**Comment by hamilton** [comment]
@begelundmuller thanks for the thinking here ~ I think `smallest_time_grain` is probably the right option. We'll provide a bunch of time grain options to the user based on their preference in the dashboard, but setting the smallest available one is the task.
