### ISSUE TITLE
Hangs if you run a query returning a structure

### ISSUE THREAD

**Issue by wlach** [rilldata/rill-developer#184]
**Describe the bug**
Rill hangs if you execute a query like `select (col1, col2) from table;`

**To Reproduce**
Run a query like the above which returns a struct. Everything hangs.

**Expected behavior**
If it can't render or do anything, show an error and allow user to continue

**Screenshots**
N/A

**Additional context**

Seeing the following in the console:

`[Error: Data type is not supported STRUCT<col1: TIMESTAMP, col2: TIMESTAMP>]`

(columns were timestamps)

**Comment by hamilton** [comment]
Thanks for reporting ~ this is a duckdb node issue. I'll file an issue in the repository.

**Comment by begelundmuller** [comment]
From the backend perspective, this should be solved with the new runtime.

@hamilton, for context, if you have the data:
```sql
CREATE TABLE foo(bar VARCHAR, baz INTEGER);
INSERT INTO foo VALUES ('a', 1), ('a', 2), ('b', 3), ('c', 4);
```
And make the following runtime query:
```bash
$ curl --request POST \
  --url http://localhost:8080/v1/instances/INSTANCE_ID/query/direct \
  --header 'Content-Type: application/json' \
  --data '{"sql": "select (bar, baz) as col from foo"}'
```
It returns this data:
```
{
	"meta": [
		{
			"name": "col",
			"type": "",
			"nullable": true
		}
	],
	"data": [
		{
			"col": {
				"bar": "a",
				"baz": 1
			}
		},
		{
			"col": {
				"bar": "a",
				"baz": 2
			}
		},
		{
			"col": {
				"bar": "b",
				"baz": 3
			}
		},
		{
			"col": {
				"bar": "c",
				"baz": 4
			}
		}
	]
}
```

Looks like the `meta` type is currently returned as `""`, which isn't great. Will log that for when we revisit meta types (currently it just proxies the typename from the DB, but we'll want a canonical representation that's the same across backends)

**Comment by magorlick** [comment]
@begelundmuller , was this resolved by the new runtime?

**Comment by begelundmuller** [comment]
@magorlick It should be fully supported by the runtime, as demo'ed in the comment above. But I don't know if the frontend is able to handle nested fields.

**Comment by magorlick** [comment]
The frontend is not ready to handle nested fields today. We do not have plans to do this at this time. @hamilton , do we want to close out this issue as resolved because the backend no longer hangs and clarify that we do not support structs somewhere? Maybe our docs?

**Comment by begelundmuller** [comment]
@magorlick Makes sense not to support it today. The frontend might need some changes to show an error when a user runs a query that returns a struct – not sure if that's handled today.

**Comment by magorlick** [comment]
Unfortunately we do not support structs at this time, however we will be revisiting this in the future.
