### ISSUE TITLE
Show a descriptive error if server is not built

### ISSUE THREAD

**Issue by wlach** [rilldata/rill-developer#185]
**Is your feature request related to a problem? Please describe.**
When you load rill-developer (`npm run cli --silent -- start`) without running `npm run build` (or `npm run build` is not complete, or it failed for some reason) you get a non-descriptive error `Cannot GET /`.

**Describe the solution you'd like**
Show a clear error message explaining the situation and how to rectify it.

**Describe alternatives you've considered**
Could also refuse to start.

**Additional context**
N/A

**Comment by hamilton** [comment]
We've moved toward having binaries built (nightly + releases), so hopefully users will not encounter this issue generally
