### ISSUE TITLE
Support all SQL-like syntaxes

### ISSUE THREAD

**Issue by brandonmcconnell** [rilldata/rill-developer#1952]
If it isn't already supported, I would love to see support added for other SQL-like databases, e.g.:

- MySQL
- MariaDB
- PostgreSQL
- SQLite
- Oracle Database
- Microsoft SQL Server
- IBM DB2
- SAP Sybase ASE
- Teradata
- Firebird

**Comment by magorlick** [comment]
Thanks for your thoughts @brandonmcconnell !  For now we are going to focus on duckDB's engine and sql syntax. They are doing some amazing things with syntactic sugar and analytics oriented computations.  

Curious - why do you need connections to these other databases? Are you storing data in object stores?

**Comment by brandonmcconnell** [comment]
> Curious - why do you need connections to these other databases? Are you storing data in object stores?

@magorlick I use PostgreSQL for all my user data.

**Comment by magorlick** [comment]
@brandonmcconnell , that makes sense! Often raw data lands in postgres.  Have you considered orchestrating data from Postgres into an object store to be picked up by Rill?

**Comment by brandonmcconnell** [comment]
We do also use MongoDB.
