### ISSUE TITLE
Admin: Implement user invites with email accept

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#1984]
As a hack, we currently create "phantom" users when inviting a user who does not exist to an org or project. We should instead track invites in a separate table and email people to sign up. (We will not separately ask people to accept/reject invites for now. Upon signing up, all invitations should automatically be applied.)

Proposed DB schema:

```sql
CREATE TABLE user_invites (
    id UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    -- Email invited to join 
    email TEXT NOT NULL,
    -- ID of the user who sent the invite (e.g. to show something like "<admin name> has invited you to org <org name>")
    invited_by_user_id UUID REFERENCES users (id) ON DELETE SET NULL,
    -- Optional org ID and role to grant the user when accepting
    org_id UUID REFERENCES organizations (id) ON DELETE CASCADE,
    org_role_id UUID REFERENCES org_roles (id) ON DELETE CASCADE,
    -- Optional project ID and role to grant the user when accepting
    project_id UUID REFERENCES projects (id) ON DELETE CASCADE,
    project_role_id UUID REFERENCES project_roles (id) ON DELETE CASCADE,
    -- Metadata
    created_on TIMESTAMPTZ NOT NULL DEFAULT now()
);
```

Flow:

- Add an invite to the `user_invites` table when adding an org/project member whose email does not match an existing user
- Send an email to the invitee telling them to sign up
- In the signup flow, lookup in `user_invites` by email and turn all invitations into roles for the user

**Comment by pjain1** [comment]
what would be the default role if not specified ? This user will be added to all user group of the org if orgId is specified but if project id is specified then it will not be added all user group. Specifying either org or project is mandatory ?
