### ISSUE TITLE
Admin: Refactor default org creation

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#2058]
Task list:

- [x] Remove code that automatically creates a default org when creating a user
- [x] In `rill auth login`, if user is not in an org, print a help message to run `rill org create` or `rill deploy`
  - When logging in through `rill deploy`, this message should not be printed. This means `rill deploy` can't naively proxy to `rill auth login` anymore
- [x] In `rill deploy`:
  - If user is not in any orgs, try to create an org based on the Github remote org name. If not possible (e.g. if name is taken), prompt for an org name
  - If user is in an org, but has not set a default one, ask them to pick from a list

**Comment by k-anshul** [comment]
@begelundmuller Didn't fully understand the last point. You mean we shouldn't allow users with common email domains from creating any org at all either during `rill auth login` or during `rill deploy`.

**Comment by k-anshul** [comment]
If the user is already logged in but no org exists for the user(in cases like when they deleted the org or didn't complete `rill auth login` prompts) should we prompt user for org creation ?

**Comment by k-anshul** [comment]
If the user deletes their default org, should we also clear the default org? 
Should we prompt user to select another org if another org exists ?

**Comment by begelundmuller** [comment]
- Removed the requirement for blacklisting org creation
- For commands that require `cfg.Org` to be set, we should have a middleware that errors if it's not set and tells people to run `rill org create` or rill org switch`. Will create a separate issue for this.
- Yes, we should clear the default org when deleting the org. Adding it to the task list in the org delete issue.
- We should not prompt for orgs too many places, just in `rill deploy`, `rill auth login`, and `rill org switch`. Other places, erroring is okay (to keep things predictable)

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill-developer/pull/2072
