### ISSUE TITLE
`npm run build` errors out

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#206]
**Describe the bug**

`npm run build` does not appear to be working properly.

**To Reproduce**
1. get fresh install
2. run `npm run install`
3. run `npm run build`
4. see error

**Comment by hamilton** [comment]
Hmm, people can't reproduce, and neither can I!

**Comment by hamilton** [comment]
I'm seeing this again, so going to re-open it.

**Comment by magorlick** [comment]
I am also seeing this.  Adding back to Sprint 14.

**Comment by bcolloran** [comment]
@AdityaHegde  did you fix this with #380 ?
