### ISSUE TITLE
Admin: Move `Project.Variables` to separate endpoint

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#2060]
We currently return a project's variables on each `GetProject` request. Since they are very sensitive, we should only return them from a dedicated API, which requires project collaborator or higher permissions to access.

**Comment by k-anshul** [comment]
Do we want to print variable values in `rill env show` command ?

**Comment by begelundmuller** [comment]
1. Let's continue to allow printing variables for now, it will be helpful in early stages. We may want to reconsider later.
2. Let's just use the `ManageProject` permission on the project for now (don't need to consider the org-level permission, we don't do permission inheritance (yet))
