### ISSUE TITLE
Runtime: Design and implement source YAML syntax for specifying CSV column types

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#2066]
We currently rely on DuckDB's `read_csv_auto` to parse CSVs. This is not sufficient in some cases, and we should support manually specifying types for certain columns. 

One idea is to extend the YAML syntax with a generic format for specifying CSV (and JSON) column types:

```yaml
columns:
  col1: type1
  col2: type2
```

We could leverage the type names in our generic schema format [here](https://github.com/rilldata/rill-developer/blob/2870dadda68052347044f78bb877f13082887f2f/proto/rill/runtime/v1/schema.proto#L5), and map them up to DuckDB syntax and pipe it into the `read_csv_auto` calls when ingesting data into DuckDB.

**Comment by esevastyanov** [comment]
[Published](https://www.notion.so/rilldata/YAML-syntax-for-CSV-JSON-schema-9ef42c9affae4ddeac21227803c1caca) two approaches of how this may look like @begelundmuller
