### ISSUE TITLE
bring dash config error messages into frontend as TS enums

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#2083]
Is it possible to get enums for these in TS? I can do this manually but it seems more robust to have these generated.

https://github.com/rilldata/rill-developer/blob/81663f3081060312eeadae4abd38f565058be2cf/runtime/services/catalog/migrator/metricsviews/metrics_views.go#L19-L26

**Comment by begelundmuller** [comment]
I can't think of an easy way right now to generate these in TypeScript. The only Go-to-TS codegen we have are the protobufs, and these error messages are buried in a pretty different package.

As a short term fix, I suggest just manually copying them. But I'll think some more about how we can facilitate this with the new reconcile.

**Comment by hamilton** [comment]
No worries, that's what I did! Thanks.
