### ISSUE TITLE
Support detecting format for compressed parquet files `file.parquet.gz`

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill-developer#2119]

**Comment by nishantmonu51** [comment]
@esevastyanov : Can you please take a look ? 
The relevant code to infer format would be in connectors.go 
+cc @k-anshul : For any help.

**Comment by esevastyanov** [comment]
As for the applying a compression while writing to a parquet file:
> Compressing the entire file (a) does not work because reading Parquet files requires jumping around to random locations, which is not possible in compressed files, and (b) has essentially no effect because the Parquet files are already compressed internally, and compressing the file twice will not accomplish much.

https://github.com/duckdb/duckdb/issues/2715#issuecomment-984431966
