### ISSUE TITLE
`humanizeDataType` does not properly handle `null` values

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#2123]
We caught this in a partner dashboard. We have a temporary fix here (https://github.com/rilldata/rill-developer/pull/2122) but it would be good to make sure our behavior matches the user expectation.

**Comment by djbarnwal** [comment]
For null values we are using various formatting styles. We show `null`, `no data`, `Φ` or an empty string at different places. We need to consolidate those stylings for a better UX.
