### ISSUE TITLE
Docs: Setup auto-generated Docusaurus pages for CLI

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#2135]
We would like to auto-generate CLI docs in in Docusaurus. In terms of navigation, Github has a nice CLI docs page to draw inspiration from: https://cli.github.com/manual/index.

The CLI library we use, Cobra, has support for generating Markdown CLI docs, which we might be able to leverage: https://github.com/spf13/cobra/blob/main/doc/md_docs.md#customize-the-output.

See this branch for an early prototype: https://github.com/rilldata/rill-developer/commit/3236b91194b9a80eb0d228a54ac80b6d67367786.

One question is whether to generate the docs in a sub-section of the "References" section in the sidebar, or in an entirely new tab. We should investigate options and discuss before implementing.

Task list:

- [x] Setup generation of CLI docs in Docusaurus (`docs/`)
- [x] Add command in Makefile to generate CLI docs

**Comment by egor-ryashin** [comment]
> One question is whether to generate the docs in a sub-section of the "References" section in the sidebar, or in an entirely new tab

References (or just Reference) seems reasonable for every auto-generated content.

**Comment by begelundmuller** [comment]
Closed by #2152
