### ISSUE TITLE
Allow an option to turn off time period comparisons in the dashboard

### ISSUE THREAD

**Issue by rillsidd** [rilldata/rill-developer#2179]
Today, by default in Rill Dashboard, the data is *always* compared to a previous time period. The previous time period is set by default but the user can change this. 

There are scenarios where a user may only want to analyze data for a certain time period and dive into the data and not necessarily look at changes over time. There should be an option available in the dash to disable time over time comparison if not needed (this may also help with dashboard performance).

**Comment by hamilton** [comment]
Discussed solution – add a way to turn comparisons off in the menu. Steps to implement:
- get microcopy right
- have this toggle some kind of comparison on / off bit of state in the DashboardStore. Can be a new field in `TIME_COMPARISON` in the `config.ts` for the time library that we simply set as the default, with null for both start and end.
- ensure that if we have a `DEACTIVATED` key (or whatever we call it), we turn off comparisons.
