### ISSUE TITLE
Metrics Explorer: implement Leaderboard component

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#218]
Description

Ask

each row of the leaderboard will be a button with the following flex components contained within it:

    ◦ icon – shows what kind of interaction has happened, e.g. “include”, “exclude”, “compare”

    ◦ label – the value materialized in the table, with ellipsis truncation

    ◦ value numbers – any amount of numbers representing numbers, change Δs / %s, etc.

        ▪ main metric ~ it’d be useful to improve the number representations to be more scannable.

    ◦ ➡️ any additional viz – this wasn’t in the original, but it’d be useful

    ◦ tooltips – the button itself should have a tooltip of some kind

**Comment by hamilton** [comment]
I think this is technically half-done. We need to clean this up before we can say the leaderboards are ready to ship.
