### ISSUE TITLE
switch out code editor

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#220]
**Initiative**
We are using a ramshackle codemirror 6 thing I put together in a short period of time. We need something that works a bit better. Leaving this epic as a stub for the implementor / lead to create a proposal and tasks against.

**Resources**
https://www.notion.so/rilldata/Replace-Code-Editor-6975c0ef28da4c91a6c68cd6cff2f371

**Checklist of Issues**
- [ ]

**Comment by magorlick** [comment]
An investigation into our code editor resulted in continuing forward with CodeMirror, thus there was no work to be done here.   Next steps feed into improving the CodeMirror experience in  https://github.com/rilldata/rill-developer/issues/265.
