### ISSUE TITLE
investigate the non-deterministic test failures

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#224]
We've known for a second that some parts of the test suite sadly appear to be non-deterministic as implemented now. We've also punted on fixing this in favor of getting out the door quickly. It's time to fix the remaining non-deterministic tests since they seem to be failing more often than not now.

This test fails regularly (reported in #207)
```
test/functional/EntityStatus.spec.ts
```
These tests seem to fail intermittently
```
test/functional/DataLoader.spec.ts
test/functional/StateSyncService.spec.ts
test/functional/DuckDbConnection.spec.ts
```

**Comment by AdityaHegde** [comment]
Hasnt been a problem in some time. Closing the stale ticket.
