### ISSUE TITLE
Docs: Cloud launch burndown

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill-developer#2371]
### Burndown list of rill cloud related documentation 

High priority
- [x] Merge local and cloud quickstart, Add a quick flow diagram for quickstart (@magorlick )
- [x] Add docs explaining project artifacts structure (@nishantmonu51 )
- [x] Add docs explaining Github integration (@nishantmonu51 
- [x] Add docs for user management - document roles and permissions on org and project level (@begelundmuller ) 
- [ ] ~~Change rill starter project to OpenRTB~~
- [x] Link to sample demos in docs (@cohenscottr : Has a list of demos we would want to put) (Katie and @cohenscottr )
- [x] Review CLI reference docs (@nishantmonu51 ) 

Medium/Low priority
- [x] Document deploying from a custom branch (@ericpgreen2)
- [x] Document support for domain whitelisting
- [ ] Document deploy steps to invite SRE/ Ops team admin
- [ ] Document free cloud plan limits - probably goes to Rill website
- [ ] Document an example for ingesting from a set of partitioned files, glob support
- [x] Document monorepo support 
- [ ] Document glob pattern support. Also update import-data.md where it says we support loading single file at a time

**Comment by begelundmuller** [comment]
The only major todo left here is documenting glob support. Created a separate issue for it here: https://github.com/rilldata/rill-developer/issues/2558

Closing this issue as cloud is now launched 🎉
