### ISSUE TITLE
Rill is freezing for some users on Chrome

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#2379]
**Describe the bug**
The UI keeps freezing on Chrome for some users, seems ok on Firefox.

**Expected behavior**
Rill shouldn't freeze.

**Screenshots**
![image](https://github.com/rilldata/rill-developer/assets/5587788/61af56c6-2c4b-442f-9dae-195aca37b943)

rill version 0.24.3 (build commit: 7e8fe848 date: 2023-05-04T15:34:36Z)
M1 Macintosh

**Additional context**
https://discord.com/channels/959796421832343562/959796422281138247/1104361484882030724

**Comment by hamilton** [comment]
I attempted to reproduce this on my machine w/ the same version of Rill – and on an M1 as well – but no luck.

**Comment by magorlick** [comment]
Thank you for trying to reproduce this! I couldn't either with the information given.  I will close this out for now as can't reproduce.
