### ISSUE TITLE
Runtime: Fix issues when Github installation has been removed

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#2411]
We are seeing some odd behavior in the runtime for instances where the Github installation has been removed. Examples:

1. There are calls to `ListCatalogEntries` that run for an insane amount of time. For example, [here's one](https://rill.datadoghq.com/apm/traces?query=%40_top_level%3A1%20service%3Aruntime-server%20env%3Astage%20status%3Aerror&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanID=12800487505332662021&spanType=service-entry&timeHint=1683661872286&trace=AgAAAYgCEVyeqCzGUAAAAAAAAAAYAAAAAEFZZ0NFWGQxQUFCNmUxQjdoell2NWtPegAAACQAAAAAMDE4ODAyMTctNWU2Mi00ZDEyLWIzMzgtOThmMjRhMjZhNmIz&traceID=12917386887318019536&start=1683281672699&end=1683886472699&paused=false) that failed after 53 minutes!
2. Here's a place I encountered the bug from the CLI:
```
> rill project reconcile --project snl-demo --reset
Error: rpc error: code = InvalidArgument desc = could not refresh installation id 37079251's token: received non 2xx response status "404 Not Found" when fetching https://api.github.com/app/installations/37079251/access_tokens (InvalidArgument)
```
3. When visiting these projects in the UI, the UI just hangs, showing no content or error messages

Task list:

- [ ] There's some exponential retry logic wrapping Github in `runtime/drivers/github`. It should not trigger on 404 errors like this, and it should never be able to run for more than ~1 minute (how is 53 minutes even possible?). Maybe we should remove the retries altogether, return the Github error, and instead let the user manually run `rill project reconcile` again?
- [ ] We should not trigger a `git pull` (calls to `RepoStore.Sync`) in other calls than `Reconcile`. In `ListCatalogEntries` and `ListFiles`, it should just return whatever is available. If no clone/pull has run it, the results of those RPCs should just be empty.
- [ ] When an installation is removed, we should receive a webhook from Github. Use it to delete any related projects.

(Please consider alternative approaches or other possible related bugs to the above.)

**Comment by k-anshul** [comment]
@begelundmuller I have not been able to reproduce the high time locally on another project (When you ran the command did it also took that much time for you ?)
Could the high timing issue be related to metrics ? Is there a way to track other metrics like github API latencies/number of calls in a span ?

> Maybe we should remove the retries altogether,

IMO its better to keep the retry but change the handler to not retry on 4xx errors if possible as you mentioned. Removing the retries may also impact auto refreshes/deploy. We don't know the stability of the github APIs yet and this can lead to issues like users complaining that sometime their changes don't get deployed on the dashboard.

> it should never be able to run for more than ~1 minute

Yeah I can cancel the pull/clone after 1 minute

**Comment by k-anshul** [comment]
> Maybe even some 4xx should be retried?

I don't think any client error apart from 429 is retryable in general. I can check if the status code for failed permissions is available and can use that to begin with

**Comment by k-anshul** [comment]
On github app suspend/uninstall added changes to delete complete project for following reasons:
1. On github app reinstall the installation ID will change and currently there is no way to update this in project
2. Project reset requires that project be previously deployed.
