### ISSUE TITLE
Runtime: APIs for listing and unpacking examples

### ISSUE THREAD

**Issue by begelundmuller** [rilldata/rill-developer#2453]
We want to add support for listing and unpacking example projects from within the UI. See details [here](https://www.notion.so/rilldata/Onboarding-screen-make-it-possible-to-jump-start-an-example-project-into-an-existing-empty-projec-6a8b813e85734eb3a6b7be2aacd19f8f).

`cli/pkg/examples` currently contains code that embeds example projects in the binary and allows unpacking them in `rill init` and `rill start`. 

Proposed task list – please suggest changes or improvements:

- [ ] Move the `cli/pkg/examples` logic into `runtime/pkg/examples` (adapt the `Makefile` accordingly)
- [ ] Adapt the `Makefile` to embed examples from https://github.com/rilldata/rill-examples instead of `examples` (delete that directory)
- [ ] Add a new runtime RPC `ListExamples` that returns example names (their directory name), titles and descriptions (from their `rill.yaml`) extracted from the embedded examples
- [ ] Add a new runtime RPC `UnpackExample` that unpacks an example project into an instance's `drivers.RepoStore` (should use the interface APIs, not the file system directly)
    - It should take a parameter `force=true`. It should first scan for conflicts and return an error instead of unpacking unless `force=true`.
- [ ] Adapt logic in `rill init` and `rill start` to unpack examples by calling functions on `runtime.Runtime`
- [ ] (Maybe: rill start should no longer initialize an empty project on start)

**Comment by k-anshul** [comment]
@begelundmuller Just to confirm we have to copy examples manually from `https://github.com/rilldata/rill-examples` to `examples` right and not programmatically in `Makefile`.

**Comment by begelundmuller** [comment]
> @begelundmuller Just to confirm we have to copy examples manually from `https://github.com/rilldata/rill-examples` to `examples` right and not programmatically in `Makefile`.

No, no manual copying. You should add a step in the `Makefile` that `git clone`s the examples and copies them into `runtime/pkg/examples/embed` (or whatever the directory will be).
