### ISSUE TITLE
Queries failing for `TIMESTAMPTZ` type

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#2573]
**Describe the bug**
DuckDB queries are failing for columns with the `TIMESTAMPTZ` type. Both profiling queries and dashboard queries.

**To Reproduce**
This works:
```sql
SELECT TIMESTAMP '1992-09-20 11:30:00' + INTERVAL '1 day' * (n - 1) AS date
FROM GENERATE_SERIES(1, 100) AS s(n);
```

This fails:
```sql
SELECT TIMESTAMPTZ '1992-09-20 11:30:00' + INTERVAL '1 day' * (n - 1) AS date
FROM GENERATE_SERIES(1, 100) AS s(n);
```

Here's the error:

"Binder Error: No function matches the given name and argument types '+(TIMESTAMP WITH TIME ZONE, INTERVAL)'. You might need to add explicit type casts. Candidate functions: +(TINYINT) -> TINYINT +(TINYINT, TINYINT) -> TINYINT +(SMALLINT) -> SMALLINT +(SMALLINT, SMALLINT) -> SMALLINT +(INTEGER) -> INTEGER +(INTEGER, INTEGER) -> INTEGER +(BIGINT) -> BIGINT +(BIGINT, BIGINT) -> BIGINT +(HUGEINT) -> HUGEINT +(HUGEINT, HUGEINT) -> HUGEINT +(FLOAT) -> FLOAT +(FLOAT, FLOAT) -> FLOAT +(DOUBLE) -> DOUBLE +(DOUBLE, DOUBLE) -> DOUBLE +(DECIMAL) -> DECIMAL +(DECIMAL, DECIMAL) -> DECIMAL +(UTINYINT) -> UTINYINT +(UTINYINT, UTINYINT) -> UTINYINT +(USMALLINT) -> USMALLINT +(USMALLINT, USMALLINT) -> USMALLINT +(UINTEGER) -> UINTEGER +(UINTEGER, UINTEGER) -> UINTEGER +(UBIGINT) -> UBIGINT +(UBIGINT, UBIGINT) -> UBIGINT +(DATE, INTEGER) -> DATE +(INTEGER, DATE) -> DATE +(INTERVAL, INTERVAL) -> INTERVAL +(DATE, INTERVAL) -> DATE +(INTERVAL, DATE) -> DATE +(TIME, INTERVAL) -> TIME +(INTERVAL, TIME) -> TIME +(TIMESTAMP, INTERVAL) -> TIMESTAMP +(INTERVAL, TIMESTAMP) -> TIMESTAMP +(TIME, DATE) -> TIMESTAMP +(DATE, TIME) -> TIMESTAMP +(ANY[], ANY[]) -> ANY[]"

**Expected behavior**
I'd expect queries to work with the `TIMESTAMPTZ` type.

**Additional context**
This is on `v0.27.1`

**Comment by begelundmuller** [comment]
Closed by https://github.com/rilldata/rill-developer/pull/2568
