### ISSUE TITLE
SQL Editor: remove the esoteric keywords from the autocomplete suggestions

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#267]
Current keywords include: `whenever`, `work`, `write`. These aren't used in everyday SQL and distract from the more substantive suggestions.

**Comment by bcolloran** [comment]
qq on this: are there other SQL keywords that we don't allow because they are not applicable to modeler? @hamilton i think you mentioned that `CREATE TABLE` queries are not allowed, is that right? If so, should we remove those keywords as well? And would there be anything else in that category?
