### ISSUE TITLE
Dashboard UX: implement time grain selector

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#310]
This should be a straightforward menu-button component.

<img width="675" alt="Screen Shot 2022-05-27 at 6 50 14 AM" src="https://user-images.githubusercontent.com/95735/170713531-ec82d293-ce78-42a4-a6a3-62bbb88742e3.png">

**Comment by hamilton** [comment]
This could be assigned to someone as well.

**Comment by magorlick** [comment]
@ericpgreen2 start with a proposal
