### ISSUE TITLE
Metrics defintion UI: prototype redux for state management

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#311]
We're shifting over our state management model for the metrics explorer to a more traditional client-server relationship. This is primarily a frontend task. If we can get the right relationship in this area, we should generalize it to the rest of Rill Developer over time.

- take the state model in `/dev/leaderboard` or `/dev/explore` and refactor it using `redux-toolkit`.
- clean up the state model structure itself, if possible.

**Comment by hamilton** [comment]
@AdityaHegde @bcolloran I think this is what the `metrics-explore` PR was about. Can you confirm, and if so could you please add `closes #311` to the PR to link it?

**Comment by magorlick** [comment]
@AdityaHegde @bcolloran, gentle reminder this needs your comment.

**Comment by bcolloran** [comment]
We are indeed using Redux to manage state for some/much of the work in the `metrics-explore` branch. I would consider the work we are doing in that branch a prototype of patterns for using redux in the app, so I've updated the title of this issue to reflect that scope.

I would say that almost all of the app state needed for the Metrics Definition UI is now in redux. I'll let @AdityaHegde comment on the status for the Explorer view, as I have not touched that part of the code.

**Comment by AdityaHegde** [comment]
The metrics-explore PR has too may tickets. I am closing them as when i commit into it. We can do the same with this.
