### ISSUE TITLE
[Epic] Metrics Explorer: implement the MVP metrics API backend prototype

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#312]
**Initiative** 
implement a new backend response structure that works with #311. This should (1) leverage the priority queue so that we can cancel / enqueue lots of updates and (2) should run queries and return the response.

_Description_
Implement a new backend response structure.

_Problem Statement_
We need robust API calls that power the front end explore experience.

_Definition of Done_
This should (1) leverage the priority queue so that we can cancel / enqueue lots of updates and (2) should run queries and return the response.

**Resources**
https://www.notion.so/rilldata/Implement-the-MVP-metrics-API-backend-prototype-c7df760666674b718bd49c9e58170580

**Checklist of Issues**
We will need the following API calls. Some of these are contingent on a metrics definition to be created.
- [x] #322
- [x] #323
- [x] #324
- [x] #441 
- [x] #442
- [x] #448 
- [x] #449

**Comment by magorlick** [comment]
@AdityaHegde , could you put an update in this epic letting us know how it is going?  I see two of these issues in review, is that part of your ongoing discussion with @bcolloran ?  If not, where is your work related to his asks documented in issues or epics?

**Comment by AdityaHegde** [comment]
There is a working branch for all these tickets : https://github.com/rilldata/rill-developer/pull/383. I also have backend APIs for metrics definition editor in the same PR along with the UI for metric explore.

**Comment by AdityaHegde** [comment]
All the changes are in the working branch #383 along with some basic UI from #204
