### ISSUE TITLE
Metrics Explorer: improve `VirtualizedGrid.svelte`

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#315]
[stub]

I have a very basic virtualized renderer for long lists of leaderboards. I would like someone to spend time with it and make sure that it is very solid. Please see the dev route in `/dev/explore` and find the `VirtualizedGrid.svelte` component.

Without a virtualized renderer for leaderboards, we will have substantial UI jank.

The component is lightly adapted from [this one](https://github.com/sveltejs/svelte-virtual-list/blob/master/VirtualList.svelte).

Ideally, it would have the following:
- rendering should be very smooth in leaderboards. No jank.
- it should know to render the leaderboard when it is just out of view in the viewport.
- you don't have to go with this component. But please consider implementing your own before pulling in someone else's library. We want to reduce the number of dependencies on 3rd party code if possible.

This could be a good ticket for anyone who wants to go deep on virtual lists. It's entirely a frontend task.

**Comment by hamilton** [comment]
@AdityaHegde or @ericpgreen2 – could y'all clarify the progress on this, if there has been progress made? We need to clean this up for the metrics explorer. There is some jank to my implementation.

**Comment by ericpgreen2** [comment]
Aditya and I discussed that I'd first address #316, in which I'm implementing an infinite scroll to add more rows to the preview table. Then, after my work is done, he's going to work on the virtualization aspect.

I'm actually working on #316 right now and think I'm close – will finish either tonight or tomorrow.

**Comment by bcolloran** [comment]
I believe we shipped this in 0.8 https://docs.rilldata.com/notes/0.8 -- closing as complete, please feel free to reopen if this is still needed for some reason, or perhaps file a new issue with updated requirements
