### ISSUE TITLE
User Onboarding : Use vercel/pkg to build rill-developer for different platforms

### ISSUE THREAD

**Issue by AdityaHegde** [rilldata/rill-developer#325]
We need to build rill-developer using vercel/pkg. We need to build this on different platforms because of duckdb.

We will have different travis-ci jobs for different platforms that pushes binaries to the release.

**Comment by magorlick** [comment]
We are not seeing binaries for all operating systems and need to reopen this issue.  The definition of done provides:

- [ ] Binaries for Mac (M1 and Intel), Linux and Windows available in the release.
- [ ] Updated our instructions on how to execute this work for releases moving forward.  Please link out to Notion docs here.  
- [ ] The generated binary files should all have the appropriate extensions to open correctly upon install.
- [ ] The correct developer signing identification should be present for iOS gatekeeper https://developer.apple.com/developer-id/

**Comment by magorlick** [comment]
This work is blocked.  @AdityaHegde is waiting to hear back from Lindsey on the correct developer signing identification.

**Comment by AdityaHegde** [comment]
@magorlick They don't need any extensions to run. M1 mac will need a separate binary to work.

**Comment by DavisVaughan** [comment]
Are you sure it doesn't need an extension? I just downloaded `rill-macos-x64` and it treated it like a text file. I'm not sure how to use it to install rill

**Comment by ericpgreen2** [comment]
Hey Davis, we need to improve this workflow, but for now, here are a few more steps:
- Run `chmod a+x <path/to/binary>` to make the file an executable. You don't need to add a file extension.
- Run `xattr -d com.apple.quarantine <path/to/binary>` to "trust" the application. We haven't yet registered the app with Apple, so Apple's default is to prevent you from opening it.
- For convenience, you'll want to make an alias for the executable, e.g. `alias rill = <path/to/binary>`

I think that should work for you, but please let us know if it doesn't!

**Comment by DavisVaughan** [comment]
Ah, that worked. Thanks!
