### ISSUE TITLE
Add ability to see more results in the preview table

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#397]
To address this incrementally:
- Show 100 results instead of 25
- Add manual pagination
- Add infinite scroll

Possibly skip manual pagination and go directly to infinite scroll.

**Comment by bcolloran** [comment]
Update: we now show 150 rows in the table.

@ericpgreen2 has there been any decision about pagination vs infinite scroll? Should we update this issue title to cover one of those topics, or close this and start a new issue? I'm guessing those might be epic-sized topics with additional requirements for the API?

**Comment by bcolloran** [comment]
oh i see that in #316 @hamilton mentions a preference to not add buttons, which sounds like infinite scroll

**Comment by bcolloran** [comment]
@ericpgreen2 i think this issue may be redundant with #316 actually -- the issue titles are basically identical. I'll close this in favor of that one, but please feel free to revert if that is the wrong call
