### ISSUE TITLE
Binaries integrated into the User Journey and readme.md

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#420]
**Issue**
Once we have working binaries we need to update our user-facing documentation to clarify the install flow.

**Importance**
If we don't tell users how to access the new features or integrate them into our user journey they won't benefit from the changes.

**Definition of Done**
Update our install documentation and install tooling to leverage these binaries.

**Comment by bcolloran** [comment]
GH note above says this was moved to closed in sprint 19, but apparently the automation didn't trigger, so closing manually
