### ISSUE TITLE
Automated shipping of binaries in the Release

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#422]
**Is your feature request related to a problem? Please describe.**
We currently automatically build rill-binaries for x86 and upload them to assets section in a release.

**Describe the solution you'd like**
We should update our npm package to install these binaries instead. This will cut down on install time needed for duckdb compile.
We can look into publishing pip and brew packages that do the same.

**Comment by bcolloran** [comment]
note from @AdityaHegde in slack: "X86 binaries are automated. Apple silicon support needs to be there in Travis before we can do it. So for now no manual step needed"

**Comment by bcolloran** [comment]
i think this work was completed, or that in any case the conversation about managing releases has moves on in the last couple months. Closing this issue as done/stale, can be reopened if needed but might be better to file new issues as needed that have the latest requirements.
