### ISSUE TITLE
UI hangs / is non responsive when running a query/profiling a big model

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#446]
**To Reproduce**
- start a query on a large enough dataset that it takes a while for profiling results to return e.g. `select * from nyc311_reduced`
- try hovering on things that should have tooltips, clicking on "sort" dropdowns, expanding/collapsing sidebar items
- nothing happen, UI is frozen; no tooltips or other interactions
- also, the spinner does not start right away, it hangs for a while before starting up (when profile results seem to start streaming in)

**Expected behavior**
- starting the query immediately starts the activity spinner
- the UI remains responsive for things like tooltips, deleting existing models (other menu actions), expand/collapse, etc

**Comment by hamilton** [comment]
Having trouble reproducing this now. Will close for the time being, and if we find the issue again, we can re-file.
