### ISSUE TITLE
The three dot menu and table tool tip overlap on three dot menu hover.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#451]
**Describe the bug**
The three dot menu and table tool tip overlap on three dot menu hover.

**To Reproduce**
1. Load a data set
2. Hover over the source's name
3. move your mouse to hover over the three dot menu
4. See the delete three dot menu cover the tool tip in a way that suggests you can delete the workspace.

**Expected behavior**
The tool tip for the table is not present when a user is hovering over the three dot menu.

**Additional context**
![Kapture 2022-06-28 at 14 05 22](https://user-images.githubusercontent.com/5587788/176264908-de1a091c-7e0f-4dd9-99d0-c341774ce416.gif)

Result of this feature change: https://github.com/rilldata/rill-developer/issues/399

**Comment by ericpgreen2** [comment]
Closing this since this issue doesn't exist in `main` anymore.

Addressed Brendan's comment here: https://github.com/rilldata/rill-developer/pull/474
