### ISSUE TITLE
[METRICS DEFINITION UI] add previews of metrics definitions in left hand nav

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#480]
Metrics definitions should have previews in the left hand nav column that follow a similar template as the existing previews for models and tables.

- each metrics definition line item should have a collapsible/expandable preview
- the preview should have three sections
    - a _time dimension_ section, which will have just one sub-entry, and can reuse the existing summary component for time series data
    - a _measures_ section, which will have one sub-entry per measure, and which will need a metrics preview sparkline that shows the aggregate measure over the time dimension
    - a _dimensions_ section; one sub-entry per dimension, can reuse existing cardinality previews

figma link: https://www.figma.com/file/HrQV6k6wSK4yER4SPZ0290/metrics-definition-UI?node-id=25%3A18171

screenshot of rough mock:
![image](https://user-images.githubusercontent.com/2380975/177407120-ea0f6a54-5e70-4cff-9bb6-3362295dfbcc.png)

(notes about the mock: (a) the agg. measure sparkline needs a little thought and refinement (b) the "sort" menu for the agg. measures needs some thought; "sort by type" in particular does not make sense)

**Comment by bcolloran** [comment]
@magorlick this chunk of work could be taken on by @djbarnwal. IMO it could also be delayed to cut scope before the release -- I think the nav preview functionality is a smaller marginal value add for the metrics definition workflow than for other parts of the app, and I've been thinking of it as more of a nice-to-have to maintain design parallelism with other views than a critical feature

**Comment by magorlick** [comment]
Thank you for flagging!  I agree I think this is nice to have for the MVP, but not strictly necessary.  We will see if we have time and keep it in the backlog for now.
