### ISSUE TITLE
Metrics Explore: leaderboards should have all the state of the `DimensionDefinition`

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#501]
The leaderboards are not bringing in the state of hte `DimensionDefinition`, so we cannot use the actual human-readable name defined, the description, or any of the other properties.

The leaderboards should have (1) the `dimensionDefinition` and (2) the `values`. Something like this:

```typescript
interface Leaderboard {
   values: LeaderboardValue[],
   dimensionDefinition: DimensionDefinitionEntity
}
```

From there, we should be using the keys in the dimension definition directly instead of making up a new `displayName` field.

**Comment by AdityaHegde** [comment]
Might be better to have values in `DimensionDefinition` slice. That way there is no data duplication and no chance of inconsistancy.

**Comment by hamilton** [comment]
Chatted with Aditya about this:
- he's going to make sure that the relationship between leaderboards and dimensions are similar to the relationship between measures in explore and the measure definitions. WHen I update the measure definition, it updates automatically in explore. The same should be true for the dimensions / leaderboards. 
- Once I have that, I can thread in the UI for this. I'll file a separate issue.
- a solution to this will also close out #502

**Comment by AdityaHegde** [comment]
I guess the 2nd option of adding IDs in MetricsExplore and getting the full dimension and measure from their respective slices is better then? That way there is no duplication of data other than the ID itself.
