### ISSUE TITLE
Update onboarding instructions for Metrics Config and Explore

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#515]
**Issue**
Our onboarding instructions are only outlining how the application works for data ingestion and data modeling.

**Importance**
When we launch metrics exploration we want to give users a more complete set of instructions on what they can expect.  This blocks our launch.

**Definition of Done**
Update the instructions seen when you launch the application and have no assets selected to include the metrics config and explore.  This work should be done and commented out and needs the icons updated.

**Screenshots**
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/5587788/178726733-dcc5a417-8b25-44f6-b575-1c49b8f8bae9.png">

**Comment by ericpgreen2** [comment]
Closed by #570
