### ISSUE TITLE
"rename" menu item show up in the dots menu for models and metrics, but it only does anything for sources

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#541]
**Describe the bug**
"rename" menu item show up in the dots menu for models and metrics, but it only does anything for sources

![image](https://user-images.githubusercontent.com/2380975/179036576-033a971f-a454-409b-b487-380b57c10225.png)

@ericpgreen2 fyi

**Comment by ericpgreen2** [comment]
Closed by #559
