### ISSUE TITLE
"Query in workspace" should instantly move the SQL Editor to the new model, rather than wait for the compute to finish

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#542]
When clicking "query in workspace" on a medium-sized source, like the `flights` dataset of 2M rows, the SQL Editor waits to open up the new model (the `select * from {source}`) until the computation completes.

The SQL Editor _should_ switch to the new model instantly, where the user can wait for the computation to complete (by observing the loading spinner).

**Comment by magorlick** [comment]
@ericpgreen2 , is this still a problem?

**Comment by ericpgreen2** [comment]
Nope, I'll close!
