### ISSUE TITLE
Incomplete metrics are being run through Explore and causing the server to hang.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#546]
**Describe the bug**
Incomplete metrics are being run through Explore and causing the server to hang.

**Expected behavior**
Exclude incomplete metrics and dimensions from being run in Explore. 
Present a validation error icon in Metrics config

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5587788/179062977-59dc2266-6531-42c4-ad30-20b03700e9ae.png">

**Comment by magorlick** [comment]
An empty dimensions row doesn't freeze. the server, but it does add a weird leaderboard that is empty with no title. 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/5587788/179066872-ac42780f-f423-4bd5-b104-b7c376951e60.png">

**Comment by AdityaHegde** [comment]
@magorlick Please verify the fix #563
