### ISSUE TITLE
Expanded leaderboards after clicking “see more” collapse when scrolling or selecting filters

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#557]
**Describe the bug**
 I don’t expect the leaderboard to collapse when I scroll. 
 I don’t expect the leaderboard to collapse when I am selecting filters.  

**Expected behavior**
Leaderboards expanded view should remain open while a user scrolls or selects filters.
A leaderboard can be collapsed when a user clicks "see less"

**Comment by hamilton** [comment]
This specific feature will be removed when we implement larger detail tables, since this toggle will take the user to a larger dimension table. Will close
