### ISSUE TITLE
Deleting an active Metrics Definition makes the view defunct

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#575]
Here's a gif of deleting an active Metrics Definition while you're on the edit page.

![Kapture 2022-07-15 at 17 36 09](https://user-images.githubusercontent.com/14206386/179327469-338f678f-bbbd-47db-9fd3-fdd87dcd51b8.gif)

Additionally, deleting a Metrics Definition from its active Explore view also causes problems.

Instead, deleting an active Metrics Definition should probably make the workspace blank or set another Metrics Definition as active.

**Comment by AdityaHegde** [comment]
This is fixed in #561
