### ISSUE TITLE
Dashboard UX: Line chart enters a state of continuous scroll

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#576]
![Kapture 2022-07-15 at 17 54 48](https://user-images.githubusercontent.com/14206386/179328126-a431b1cf-85cd-48b9-ad35-0c4afd1f69f0.gif)

To get into this state: 
- define a metrics definition
- go to the Explore page and set a small recent time range like "Last hour"
- go back to edit the model to truncate the time range to exclude the time range you had in Explore
- go back to the Explore page and observe the chart seemingly infinite scroll (though, the smaller the date range you truncate, the quicker the scroll will come to a stop)

**Comment by AdityaHegde** [comment]
This is fixed in #561
