### ISSUE TITLE
add more detailed validation messages for measure aggregation expressions in the Metrics Designer

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#589]
working on #588, I noticed that currently the only value that seems to be stored in `expressionValidationError.message` is ever "Unexpected end of input". It would be awesome if we could get more detailed feedback.

Here are a few brainstorms of the kinds of things that could be useful:
- when a user has an invalid column name: `SUM(foo)` --> "The column `foo` is not present in the data model `bar`"
- an invalid aggregation function: `SUMM(column)`  --> "`SUMM` is not a valid SQL aggregation expression"
- invalid tokens: `SUM(col_1) # COUNT(col_1)` --> "The character `#` is not allowed in SQL expressions"
- invalid subexpression -- CASE, SELECT, WHERE ... --> "Measure aggregation expression may only contain aggregation functions and arithmetic operations"  _(Note: I don't think we've formally defined what kinds of expressions are valid anywhere, this is just an example)_

fyi @magorlick  for other feedback ideas and @AdityaHegde  to comment on what is available today. Also fyi @begelundmuller for the kinds of feedback we'd like to give users

**Comment by magorlick** [comment]
This set looks good! Finding a way to clearly communicate what is possible without guess and check is also desirable on top of the invalid subexpressions. We should get internal clarity on what we want here.  As a user, I might look up what aggregations are possible on duckDB, and I am pretty sure we don't support many of these options: https://duckdb.org/docs/sql/aggregates

Getting wilder - but I can also imagine people might think it is possible to put an entire select statement in there to pull in an interesting value (like a denominator from another source as a subselect). 

Window functions should also be pushed back to the transformation and aren't really aggregates anyway.  Might be a nice thing to guide users towards if they try windows.

**Comment by AdityaHegde** [comment]
Yes. The response from server is meant to have the detailed error message. It gives the info for the message to be built and the UI should build the message. Going forward we will only get the AST from the new server. So i will add the code on the UI to generate this message from the info.
