### ISSUE TITLE
Short Circuit: If a model has a timestamp column, create "go directly to dashboard" functionality

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#632]

**Comment by hamilton** [comment]
@AdityaHegde do you think we can get this button to effortlessly send the user to a dashboar the way you did for the source -> dashboard work?
<img width="643" alt="Screen Shot 2022-07-26 at 4 32 37 PM" src="https://user-images.githubusercontent.com/95735/181129767-661bafe7-cc0a-4498-9533-801e909412dc.png">

**Comment by AdityaHegde** [comment]
Yes should be straightforward.
