### ISSUE TITLE
Create a proposal for state modularization

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#639]
Map out how we'll move application state out of the server and into the client. Consider a query-caching library (like RTK-query or svelte-query) and consider the resulting scope of the global state store (Redux, Svelte Stores).

**Comment by hamilton** [comment]
Sprint 26 status:
- drafted a proposal
- get to itemized list of things to do, like the work plan

Team to meet on Wednesday – @ericpgreen2 to schedule
