### ISSUE TITLE
Linechart elements in dashboard push leaderboards out of the window at narrow sizes.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#680]
**Describe the bug**
Linechart elements in dashboard push leaderboards out of the window at narrow sizes.

**To Reproduce**
1. Init the example
2. quick start to the dashboard
3. Make sure the left navigation bar is open
4. Change the size of your browser window to a width where the leaderboard is wider than the space between the charts and the right side of the browser window.  This is about 2/3 of the width on most screens.
5. The leaderboard disappears

**Expected behavior**
I expect the last column of leaderboards to stay on the screen where less of the element is seen as the browser widow occludes the right side of the element.

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/5587788/181643763-5f183423-dec2-40ba-b907-377577f2415b.png">
<img width="1889" alt="image" src="https://user-images.githubusercontent.com/5587788/181643787-56b625da-a9fb-4e2e-8578-9e50f0818ee5.png">

**Comment by hamilton** [comment]
@djbarnwal going to assign this to you. I think the strategy should probably be to make sure the container that uses the virtualized grid component has a min-width set, and we will force a scrollbar in that instance.
