### ISSUE TITLE
Change the default timerange settings for the dashboard to reflect static data analysis.

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#685]
**Issue**
Our current dashboard default focuses the user on the last 30 days from the "most recent" or max day.  There might be utility in focusing on the most recent 30 days in the data set when it is real time data, but it can also lead to confusion because you start out zoomed in without context around what is possible.

**Importance**
I was just troubleshooting why I had no line charts in my dashboard and realized the 30 day time range default was being affected by an extreme outlier with a timestamp far out in the future.  Because this outlier was the ‘most recent’ anchor date the charts appeared empty and it was confusing what was going on. 

**Definition of Done**
The default for Rill Developer's static dataset will show All Time data on the dashboard so users can start 'zoomed out' and refine their view.

**Comment by ericpgreen2** [comment]
Closed by #682
