### ISSUE TITLE
we should have documentation about valid measure expressions

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#710]
We have zero documentation on this, nor do we have links from the metrics config. This would be quite useful for users, who will surely be confused.

**Comment by ericpgreen2** [comment]
A few ideas for it:
- We'll probably want a docs page for "Create your first dashboard", which goes through a basic end-to-end example. Given that page, an additional reference page specifically for "Creating metrics" - showing the world of possibilities - would be helpful
- One section would focus on Measures and provide at least 3-5 examples of evolving complexity
- Focus on one real world use case (e.g. metrics from an eCommerce business)

**Comment by hamilton** [comment]
closing this given the following page: https://docs.rilldata.com/defining-metrics
