### ISSUE TITLE
distinct count aggregate for bignumber viz breaks when all filtered column values are null

### ISSUE THREAD

**Issue by nishantmonu51** [rilldata/rill-developer#715]
**Describe the bug**
Add a count(distinct dimension) and then filter where the dimension value is NULL. the BigNumber viz never shows anything. 

**Expected behavior**
Would expect COUNT(DISTINCT column) to return 0 if all values are NULL.

**Comment by djbarnwal** [comment]
Fixed https://github.com/rilldata/rill-developer/pull/714/commits/173da42366f4eb2c7345a810dbc1addb600c078d
