### ISSUE TITLE
humanized leaderboard numbers should probably take into account all the data 

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#721]
I think it's a good idea for us to figure out how to avoid cases like `1345.4k` (would expect `1.34m`) in the leaderboards and `40.0k` in the axes (would expect `40k`)

the existing heuristic may need some tweaking. Could we check what the legacy dash does?

<img width="1669" alt="Screen Shot 2022-08-03 at 8 26 22 AM" src="https://user-images.githubusercontent.com/95735/182647575-ad094285-52a0-4323-b632-4711ac77e277.png">

**Comment by djbarnwal** [comment]
@hamilton Tried taking all data into account. Even though the scale chose by the algorithm remains to be `k`. This is happening because the nulls are now skewing  the results a bit. Do you think adding commas would make it look better to instead of 1353k we can show 1,353k?
