### ISSUE TITLE
Docker compose Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by ahsanshah** [rilldata/rill-developer#738]
**Describe the bug**
When using the steps for Docker-compose I get a error:  Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found.  This seems to be unique to the OS. Is there a version or workaround to address this issue?  I am using Ubuntu 18.04.  

**To Reproduce**
Follow steps for docker install via compose.  

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS

**Additional context**

**Comment by hamilton** [comment]
Thanks for the bug report.

**Comment by magorlick** [comment]
An additional report has come in "Hello There, I have the same Docker Compose problem with GLIBC_2_29 on Ubuntu 20.04.4 LTS."
