### ISSUE TITLE
Updating sql file in center panel, does auto update the name in the sidebar until page refresh

### ISSUE THREAD

**Issue by cliffordfajardo** [rilldata/rill-developer#744]
**Describe the bug**

Updating model file name doesn't autoupdate the sidebar; I have to refresh my webpage, which takes you out of focus of what you're doing

**To Reproduce**
1. Click plus (+) button in the "Models" section
2. Rename the name in the center pane
3. Observe that the .sql file name does not update

https://user-images.githubusercontent.com/6743796/183496683-1056e48a-30bb-4620-a4a5-c62bd45a8bc2.mp4

**Comment by hamilton** [comment]
I believe this was fixed a couple releases ago but I hadn't marked it. Thanks for filing @cliffordfajardo!
