### ISSUE TITLE
Feature Request: ability to rename `.sql` file name on the left sidebar

### ISSUE THREAD

**Issue by cliffordfajardo** [rilldata/rill-developer#745]
Hi Rill team,

**Describe the solution you'd like**
Ability to rename a `.sql` file name from the left sidebar; by doing the following:

1. show a "rename file" option when clicking the option menu (...)
   ![CleanShot 2022-08-08 at 12 37 31@2x](https://user-images.githubusercontent.com/6743796/183500267-af417329-0b0a-48f3-9faf-24e9c008bbd7.png)

2. Option clicking  the file name area triggers options menu 
![CleanShot 2022-08-08 at 12 38 45@2x](https://user-images.githubusercontent.com/6743796/183500623-c65dfda1-e3dd-467f-85c6-663fcf7dbc1a.png)
  - this would match common user behavior found in apps like google drive, your computer or even your text editor when you option click a file 😄 

**Describe alternatives you've considered**
Rename it by clicking the file name text in the center panel  (keep this)😄  however not seeing the option on the left sidebar was strange

**Is your feature request related to a problem? Please describe.**
Sort of related to this: https://github.com/rilldata/rill-developer/issues/744

**Comment by ericpgreen2** [comment]
Hey @cliffordfajardo, we added this feature to version `0.8.0` which we released on Thursday. Thanks for the feedback!
