### ISSUE TITLE
When CSV import error occurs, show user error message from `/table-upload` response inside the error modal to help user debug

### ISSUE THREAD

**Issue by cliffordfajardo** [rilldata/rill-developer#746]
### Describe the bug
I'm unable to import a large CSV file into the Rill app 

<br />

### Expected behavior
1. When there is a CSV file format error, display the error message from the `/table-upload` response inside the error modal
2. When the error CSV import error modal shows up, keep the modal open and allow the user to dismiss it with a X button
    - the error modal flashes appears & disappears to quickly thus you cannot read the error message; I had to video record my screen to read it

<br />

    
### Error Message from `/table-upload` endpoint:

```json
{
    "messages": [
        {
            "type": 1,
            "message": "Error: Invalid Input Error: Could not convert string 'up' to INT32 in column \"admin_status\", between line 186371 and 186625. Parser options: DELIMITER=',' (auto detected), QUOTE='\"' (auto detected), ESCAPE='' (auto detected), HEADER=1, SAMPLE_SIZE=10240, IGNORE_ERRORS=0, ALL_VARCHAR=0. Consider either increasing the sample size (SAMPLE_SIZE=X [X rows] or SAMPLE_SIZE=-1 [all rows]), or skipping column conversion (ALL_VARCHAR=1)",
            "stack": "Error: Error: Invalid Input Error: Could not convert string 'up' to INT32 in column \"admin_status\", between line 186371 and 186625. Parser options: DELIMITER=',' (auto detected), QUOTE='\"' (auto detected), ESCAPE='' (auto detected), HEADER=1, SAMPLE_SIZE=10240, IGNORE_ERRORS=0, ALL_VARCHAR=0. Consider either increasing the sample size (SAMPLE_SIZE=X [X rows] or SAMPLE_SIZE=-1 [all rows]), or skipping column conversion (ALL_VARCHAR=1)\n    at Function.getEntityError (/snapshot/rill-developer/dist/common/data-modeler-service/response/ActionResponseFactory.js)\n    at DatabaseDataLoaderActions.createTableWithQuery (/snapshot/rill-developer/dist/common/database-service/DatabaseDataLoaderActions.js)\n    at async DatabaseService.dispatch (/snapshot/rill-developer/dist/common/database-service/DatabaseService.js)\n    at async ActionQueueOrchestrator.run (/snapshot/rill-developer/dist/common/priority-action-queue/ActionQueueOrchestrator.js)",
            "errorType": 2
        }
    ],
    "status": 1
}
```

<br />

### Steps to reproduce the behavior
Import CSV file that is 66.5MB large
   <img  height="450" src="https://user-images.githubusercontent.com/6743796/183504231-5245cd75-6cca-40e5-9dea-da48bd3da922.png"/>
   
   https://user-images.githubusercontent.com/6743796/183509332-f3781a69-9c82-48eb-99b3-0fac62f626e6.mp4

**Comment by magorlick** [comment]
Hi @cliffordfajardo.  We use [duckDB's csv ingestion](https://duckdb.org/docs/data/csv) to `AUTO_DETECT` column types in Rill Developer.  This error indicates that the CSV ingestion had an unexpected type in column "admin_status" (string 'up' to INT32 in column \"admin_status\").  DuckDB is sampling to determine the type for each column and sometimes it doesn't quite get it right.  You might try using a parquet format that comes with types in the file for better results.  

We should make it easier to see these errors so people can debug. I run across this kind of issue frequently myself while exploring new data sets.  We will continue to invest in new features that make it easier to get data into the application. Thank you for filing!

**Comment by cliffordfajardo** [comment]
Hi @magorlick 
Thanks for the details - I'll try exporting to partquet

What do you think about the following related to the attached video:
- Displaying error message from the `/table-upload` endpoint in the error modal
- when CSV import error occurs, letting the error modal stay open & allowing user to dismiss it

   https://user-images.githubusercontent.com/6743796/183509332-f3781a69-9c82-48eb-99b3-0fac62f626e6.mp4

Less technical user's have may have no clue on how to open the chrome developer tools :win

**Comment by magorlick** [comment]
I think it is a great idea and I added an issue to our backlog and extended to all data ingestion. https://github.com/rilldata/rill-developer/issues/747. Thanks again for your input!
