### ISSUE TITLE
Creating a new dashboard should not show a red overlay

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#758]
When clicking on "autogenerate dashboard", sometimes a red overlay transition state appears that says "creating metrics dashboard for source". When it comes and goes quickly, it's hard to read, but seeing the red color makes it feel like something bad happened.

At the very least, we should change the color of this overlay to something more neutral. But we should also consider how this feels when the overlay comes and goes in a split second. It's frustrating when you can't read what it says because it's gone so quickly.

![Kapture 2022-08-09 at 17 23 44](https://user-images.githubusercontent.com/14206386/183784117-65fd4a9c-b078-49fa-95d9-26ba39550a61.gif)

**Comment by bcolloran** [comment]
Yeah I very much agree. In general I find these whole page takeover interstitials quite distracting, and I don't really think they're necessary. I think we should not need to prevent users from having any access to the UI while we're doing these operations, it should be possible for users to still click around, scroll, do a bit of navigation without the whole app basically locking down and freezing. It would be enough to just show a progress bar Or something to let users know when an action we're doing for them in the background is complete. but locking the UI can be a bad experience
