### ISSUE TITLE
file names that are entirely numbers and symbols fail

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#762]
**Describe the bug**
When you ingest a file name that is entirely numbers and symbols the ingestion fails.

**To Reproduce**
1. Start with a csv or parquet file you know works in Rill Developer
2. Change the name to '2022-08-09'
3. Try to import the file
5. Change the name to '2022-08-09_data'
6. Try to import the file
7. File ingests

**Expected behavior**
File names should be sanitized for the user so they can be ingested as a source.

**Comment by hamilton** [comment]
Going to work with @magorlick to figure out what we want to prepend for the source name

**Comment by magorlick** [comment]
Let's preappend with an underscore and use the current table sanitization methodology for the rest of the name.

**Comment by hamilton** [comment]
@AdityaHegde let's enqueue this for 14 if we can. We just had someone on twitter complain about it as well so it seems like this should be a straightforward fix.
