### ISSUE TITLE
Set a dev identifier in our telemetry when running in contributor mode

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#763]
**Issue**
I see lots of install_ids that must have been developers because the assets were on the branch off of main that most users couldn't see.

**Importance**
I want our metrics to be meaningful as we gain more users.

**Definition of Done**
Telemetry includes a developer identifier that helps those doing analysis filter out internal users.  We could create a bool flag in the telemetry called 'contributor' to track this and let everyone continue to get ids to debug.

**Comment by bcolloran** [comment]
Question about how our telemetry currently works: it Sounds like you are able to see the branch that people are on, does that mean you are able to filter on usage coming from the binary by looking up the git tag? I'm not sure if the tag is recorded with the branch or if we pass the tag information through at all.

Would being able to filter on usage coming from the binary be adequate for your task? That might be possible to implement by adding some kind of flag during the build step

**Comment by magorlick** [comment]
I cant see the branch people are on, but I can see the version, and we only update the version when we ship the product. Thus, you can be working on a 'version' of the product on main where you are adding features that will be released down the road.  That is what I am seeing here.

Usage coming from the binary would not be adequate. Lots of folks use npm.
