### ISSUE TITLE
Charts with negative measures are broken

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#834]
In case the measure is all negative values, the line chart seems to be broken

![Kapture 2022-08-25 at 15 10 41](https://user-images.githubusercontent.com/4402679/186632134-88e5ca69-a012-4d71-9f4b-7cfd72186766.gif)

**Comment by djbarnwal** [comment]
Got the culprit - https://github.com/rilldata/rill-developer/blob/ff4786b253627f85716041aeea5fc1fe8cf1eda0/src/routes/_surfaces/workspace/explore/time-series-charts/TimeSeriesBody.svelte#L57-L59

`yMin=0` is forcing a wrong domain for the Y axis. @hamilton Is it fine to just remove this?

**Comment by hamilton** [comment]
@djbarnwal I think it would make sense to look at the data. if there are negative values, we remove the yMin constraint. If there are not negative values (for now), we keep the 0 constraint.

Eventually, it will be useful to be able to just say if a number can ever be negative (e.g. a count, a sum on postivie-value numbers) but let's see if this works for now.
