### ISSUE TITLE
duplicate measure definitions cause an error in humanize

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#847]
This may have been fixed by the `svelte-query` branch. @ericpgreen2 will investigate if so.

**Comment by djbarnwal** [comment]
The log throws an error at https://github.com/rilldata/rill-developer/blob/97955c2308d7035fc47615aa900f1eab1b843d59/src/lib/util/humanize-numbers.ts#L144-L145

But changing the entry condition to `options?.excludeDecimalZeros && typeof formattedValue == "string"` seems to only fix a part of it. Going back the dashboard is shown but without the newly added measure's line chart. Not sure what is going wrong beyond this. No errors in the log as well

**Comment by ericpgreen** [comment]
I think you meant to tag someone else @hamilton.

**Comment by hamilton** [comment]
sorry @ericpgreen! Guess I at least know who was first to that username :)

**Comment by ericpgreen2** [comment]
Ahh apologies to number 1.

Anyways, I'm not seeing the bug on the `svelte-query` branch 👍
