### ISSUE TITLE
`rill start` shows cryptic error message when port 8080 is already in use

### ISSUE THREAD

**Issue by ericpgreen2** [rilldata/rill-developer#873]
Running `rill start` shows this error when port 8080 is already in use:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/14206386/188204985-befbda96-76df-41d4-b553-db2d9589682a.png">

To reproduce, run `rill start` in two separate terminal windows.

I'd expect a friendly error message to tell the user that port 8080 is already in use.

**Comment by begelundmuller** [comment]
This will be fixed by https://github.com/rilldata/rill-developer/issues/1190

**Comment by ericpgreen2** [comment]
Fixed in Rill version `0.16.0`
