### ISSUE TITLE
toggling items in under the filter pill causes grey background to flicker

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#897]
**Describe the bug**
 In the attached video, I'm only ever doing single clicks, but the visual feedback makes it feel like a double click (notice that the checkmark only changes state once, but the gray background flickers).

https://user-images.githubusercontent.com/2380975/189195269-db86f80c-2ec8-482a-be89-7af105debb87.mp4

**Comment by hamilton** [comment]
Good catch ~ we should not have that for a multiselect animation, only single.

**Comment by bcolloran** [comment]
oh I just assumed that was a bug in all cases, it's intentional for some case? My 2 cents: I thought it looked like a rendering bug because it felt out of place given the smooth animations we have elsewhere. I think the flicker is a bit jarring / distracting / visually noisy, and not really needed to communicate that state change, which we do with the icon and background change. I'd be in favor of taking the flicker animation out of our animation styles.

**Comment by hamilton** [comment]
I don't agree, and would prefer we tune this so that it's less of an issue. A flickering action before closing a menu is a very helpful visual that exists in many other menu implementations in web apps and OSes alike.

**Comment by bcolloran** [comment]
Ah, I think we're talking about different  things-- you mention closing the "flickering action before closing a menu", and I just noticed this flicker in the dropdowns for selecting the time grain and time horizon, and I think it's fine there to indicate that a selection has been made before closing the menu. But in the context of the filter pill, we don't immediately close the menu, and in that context the selection can be immediately indicated by toggling the X/check icon that indicates selection (in fact, in that context playing the flicker animation delays the immediate toggling of the icon).

I guess I I agree that we don't need to remove the everywhere (I can see why you like it when a click also closes a menu, it gives the user a beat to notice what happened), but I do still find it jarring and out of place in the filter pill menu, and I don't think it makes sense or is needed when we're toggling things that will remain in place (eg, we don't play a flicker animation when toggling selection in the leaderboard, the selection is indicated with other cues since the toggled item remains on screen; the filter pill menu is an almost identical context and interaction in a different location).

**Comment by hamilton** [comment]
It appears this particular issue was fixed in the filter pill in a previous release by using the available `animateSelect` prop.
