### ISSUE TITLE
CREATE SOURCE support in calcite for DuckDB

### ISSUE THREAD

**Issue by pjain1** [rilldata/rill-developer#934]
this will probably spill over next sprint as well. 
Tasks to be done - 
- [x] Parse the CREATE SOURCE statement 
- [x] Return the protobuf representation to the runtime 
- [x] Test cases
- [x] Protobuf test cases

**Comment by nishantmonu51** [comment]
More details: 

1. Get a CREATE SOURCE statement -> Runtime will pass in and get a logical AST representation. 
2. Runtime - connector for S3-DuckDB -> take the logical AST representation and write that into a DuckDB implementation.
