### ISSUE TITLE
Asset Navigation Broken on Main

### ISSUE THREAD

**Issue by magorlick** [rilldata/rill-developer#955]
**Describe the bug**
You can't create a new model or dashboard on main

**To Reproduce**
1. Click the "+" icon for a model and try to navigate to the model. You see an empty workspace with no SQL code interface.
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/5587788/192560970-d384df8e-a85c-4ce8-91b4-2312c7d99019.png">

3. Click the "+" icon and try to navigate to the dashboard. See a 404 error.
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/5587788/192561019-d207e84e-9b93-4cf2-8c38-c0f2b134f063.png">

**Expected behavior**
I expect to be able to navigate to the assets to change them with feedback surfaced in the right channels.

**Additional context**
This bug is blocking the 0.11 release.

**Comment by AdityaHegde** [comment]
Model issue is fixed after running `npm i`
