### ISSUE TITLE
Autogenerate on model throws error

### ISSUE THREAD

**Issue by djbarnwal** [rilldata/rill-developer#956]
**Describe the bug**
Autogenerate on model throws error

**To Reproduce**
1. Add a source
2. Create a model from that source but with a different name
3. Click on more actions -> Autogenerate dashboard

<img width="1508" alt="Screenshot 2022-09-27 at 8 29 33 PM" src="https://user-images.githubusercontent.com/4402679/192562305-6be20e04-e8bb-4ec8-bb2f-afa15d3bc630.png">

**Comment by AdityaHegde** [comment]
This is fixed after running `npm i`
