### ISSUE TITLE
Issue running for development locally

### ISSUE THREAD

**Issue by willeppy** [rilldata/rill-developer#971]
**Describe the bug**
I am able to run app by installing as normal package, however running a local build is breaking for me.

**To Reproduce**
```bash
# clone this repo and cd into it
npm install
npm run build
npm run cli init-example
```

Error:
```
>> npm run cli init-example                                      

> @rilldata/dev@0.10.0 cli
> ts-node-dev --quiet --project web-local/tsconfig.node.json -- web-local/src/cli/data-modeler-cli.ts "init-example"

Initializing the example project ~/rill-developer/rill-developer-example ...
Directory ~/rill-developer/rill-developer-example already exist. Attempting to initialize the project. 
/bin/sh: ~/rill-developer/web-local/dist/runtime/runtime: No such file or directory
FetchError: request to http://localhost:8081/v1/instances failed, reason: connect ECONNREFUSED ::1:8081
    at ClientRequest.<anonymous> (~/rill-developer/node_modules/isomorphic-unfetch/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

Seems like it is trying to query an endpoint unsuccessfully?

I get the same error if I run `npm run cli init-example` or `npm run cli --silent -- start --project ../manual-rill-project` where `../manual-rill-project` works as a project with normally installed rill

**Desktop (please complete the following information):**
 - MacOS
 - Chrome 105.0.5195.125

**Comment by magorlick** [comment]
Hi @willeppy , thank you for filing. Did you pull down this repo today? We just upgraded Rill Developer to 0.11 and there was a breaking change for existing project databases.  You can read more in our release notes: https://docs.rilldata.com/notes/0.11

If you pulled down this repo today and installed the Rill globally some time in the past, you might experience something like this.  I include the instructions for how to make older projects compatible with Rill Developer again below. Let me know if this helps you.

_Upgrade to duckDB 0.5.0 — We are excited to update your experience to include the new features released by duckDB in 0.5.0. Note that this is a breaking change where projects created with prior versions of Rill Developer will not be compatible.
If you encounter this error when you try to start Rill, you can fix your project by deleting `./stage.db`, `./stage.db.wal`, and `./state/*`. The next time you run `rill start` in the CLI, a new updated database will be created. You will then need to reimport your data to restore existing models and dashboards._

**Comment by hamilton** [comment]
@willeppy in case what @magorlick suggested doesn't work, you could also try to `cd` into the `web-local` directory and then running these NPM commands. We just recently moved things around in the codebase to reflect our future direction / other big components we're adding to rill developer, so there may be some rough edges until we iron things out!

**Comment by AdityaHegde** [comment]
Hi @willeppy. What is your npm version? Older 8.x versions had issues with `postinstall` not running inside npm workspaces. Perhaps that is why the app cannot find `web-local/dist/runtime/runtime`, it is downloaded during a `postinstall` within web-local.

**Comment by willeppy** [comment]
Ah I think it was the npm issue, thanks @AdityaHegde! I was using `8.6.0` then upgraded to `8.19.2` and re-installed and built and working now.
