### ISSUE TITLE
metrics description does not propogate to leaderboard tooltip automatically

### ISSUE THREAD

**Issue by bcolloran** [rilldata/rill-developer#982]
**Describe the bug**
when I update a description in a metrics definition and then go back to the dashboard, the tooltip  I see when hovering over the leaderboard (e.g. the one in the screenshot below) does not update until I refresh the page.

![image](https://user-images.githubusercontent.com/2380975/193663133-f68e3ac0-57fd-41b2-999d-1aa685bc179e.png)

**Comment by AdityaHegde** [comment]
This might have been fixed at some point. I couldn't reproduce this. @bcolloran could you confirm if you are seeing it on main?

**Comment by bcolloran** [comment]
actually, at this point (main 02cea30), it's even worse than it was when I reported it -- I can't see custom tooltips on leaderboards _at all_, even after a manual refresh:

https://user-images.githubusercontent.com/2380975/208737269-89cb730b-a6bc-4ed2-8ba3-e3cfead8d616.mp4
