### ISSUE TITLE
preview table: dragging the column to change the width does not work if the table is scrolled to the right

### ISSUE THREAD

**Issue by hamilton** [rilldata/rill-developer#985]
Seems we've had a feature regression with the preview tables. If I try to change the size by dragging, the table immediately goes back to the origin.

**Comment by bcolloran** [comment]
adding a bit of detail here: dragging on the column header to change the width actually works as long as the table isn't scrolled. As soon as you scroll to the right in the table, you can no longer adjust the column , and the table snaps back to the first column. see the attached video

https://user-images.githubusercontent.com/2380975/203168519-cd3ac751-556f-4b5b-948b-a831e5fd225d.mp4
