### ISSUE TITLE
Timestamp zoom window max bounds do not change on sidebar resize

### ISSUE THREAD

**Issue by willeppy** [rilldata/rill-developer#990]
**Describe the bug**
If I resize the sidebar and then ctrl + drag to zoom on a timestamp column, the right bound of the zoom window is stuck at the initial right bound. See video below for example

**To Reproduce**
1. Go to timestamp column
2. resize sidebar to make it wider
3. Try to zoom by ctrl + click + drag and the right bound will be stuck at the initial window size

**Expected behavior**
Zoom window is responsive

**Screenshots**

https://user-images.githubusercontent.com/13400543/194130472-952f4fb9-eec7-4362-af82-8b066ad2185f.mov

**Desktop (please complete the following information):**
 - MacOS, Chrome

**Comment by willeppy** [comment]
I think this is because `createSrubAction` is not updating on the window size change and so the clamp function is still using the old bounds

https://github.com/rilldata/rill-developer/blob/b640b8ac543ab11d2bb0ba499b1432570abde06b/web-local/src/lib/components/data-graphic/compositions/timestamp-profile/TimestampDetail.svelte#L139

**Comment by hamilton** [comment]
@willeppy Thanks for the issue! The scrub action should have some update function associated with it so that it can reactively respond to range changes.
